### ISSUE TITLE
features needed for 94X re-miniAOD

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#21864]
The initial list is to be collected by Jan 22.
@gpetruc @arizzi @franzoni 

~The deadline for PR submission is set to Jan 29 (based on the decision in ORP on Jan 23)~ The deadline was relaxed a bit.

Somewhat up-to-date list (Mar 17). A checked box corresponds to merged PRs.
- Features affecting miniAOD content:
    - [x] #22125 "Fix dE/dx hit association index"
    - [x] #22132 "Fix reading prescale values during miniAOD production"
    - [x] #21977 "New trainings for mvaTauID + one backport from CMSSW_10_0_X"
    - [x] #22042 "Backport to 9_4_X of DeepFlavour and TF API"
    - [x] #22302 Cut-based and MVA-based photon IDs and cut-based electron IDs
    - [x] #22303 MVA electron IDs 
    - [x] #22347 MET significance tuning
    - [x] #22381 High Level conditions for 2017miniAOD rereco
    - [x] #22508 PUPPI multiplicities saved in miniAOD
    - [x] #22550 to enable e/gamma IDs 
    - [x] #22623 e/gamma scale correction and smearing 
- Features not affecting miniAOD content, but needed for analysis/studies 
    - [x] #21941 "Puppi weighted multiplicities"
    - [x] #22093 "Adding capability to write out Ptrs in JetConstituentSelector"
    - [x] #22345 Fix in MET uncertainty tool for the case of jet reclustering
    - [x] #22410 "V1" electron regression modifier from 80X

**Comment by slava77** [comment]
assign reconstruction,analysis,alca

**Comment by arizzi** [comment]
EGM POG updated IDs should be included:
- first version based on prompt and MC V1 expected this week (PR for 10XY already exists)
- second version based on rereco and MC V2 in 2-3 weeks

**Comment by arizzi** [comment]
new btaggers from #19893 (that seem finally ready to be integrated?) are also needed

Need a backport in 94X of #19893 with new algorithms enabled only in the miniaodV2 campaign

**Comment by slava77** [comment]
The deadline for PR submission is set to Jan 29 (based on the decision in ORP on Jan 23)

**Comment by pablodecm** [comment]
[**@slava77**](https://github.com/slava77) commented on [23 Jan 2018, 14:47 CET](https://github.com/cms-sw/cmssw/issues/21864#issuecomment-359795315 "2018-01-23T13:47:14Z - Replied by Github Reply Comments"):
> > Need a backport in 94X of [#19893](https://github.com/cms-sw/cmssw/pull/19893) with new algorithms enabled only in the miniaodV2 campaign
> 
> [@pablodecm](https://github.com/pablodecm) [@ferencek](https://github.com/ferencek) [@mverzett](https://github.com/mverzett) please coordinate and make a PR for 94X.  
> 
> Are the training files already in 94X?

The training files are in https://github.com/cms-data/RecoBTag-Combined since tag v10-00-08, how are the data tags and releases related? Which 94X release you suggest rebasing over?

**Comment by perrotta** [comment]
Pablo de Castro <notifications@github.com> ha scritto:

> The training files are in  
> https://github.com/cms-data/RecoBTag-Combined since tag v10-00-08,  
> how are the data tags and releases related? Which 94X release you  
> suggest rebasing over?

@pablodecm: make a new PR (do not rebase #19893!!!) as usual starting  
from the latest 94X IB:
http://cms-sw.github.io/showIB.html
(which by the way right now corresponds to CMSSW_9_4_3)

**Comment by pablodecm** [comment]
@perrotta I meant rebasing the features in https://github.com/cms-sw/cmssw/pull/19893 over the latest 94XIB and pushing in a PR, not rebasing that PR. Any info on the availability of the mentioned cms-data externals in CMSSW_9_4_3?

**Comment by perrotta** [comment]
Thank you (it was just to be sure...)

About your externals, as far as I can see they are only merged in 10_0_X:
https://github.com/cms-sw/cmsdist/pull/3573
while the tag in 94X is still the previous one:
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_9_4_X/gcc630/data-RecoBTag-Combined.spec

They should be requested for 94X as well.

**Comment by mbluj** [comment]
Dear All,
as stated on last reco meeting Tau POG wants to update tau-Ids with recent BDT training. We plan prepare a PR by next Monday. 
BTW, is there a special Era expected for reMiniAOD w/ 94X or new features (here tau-Id) should become a part of the standard MiniAOD configuration?

**Comment by slava77** [comment]
On 1/24/18 3:22 AM, mbluj wrote:
> Dear All,
> as stated on last reco meeting Tau POG wants to update tau-Ids with
> recent BDT training. We plan prepare a PR by next Monday.
> BTW, is there a special Era expected for reMiniAOD w/ 94X or new
> features (here tau-Id) should become a part of the standard MiniAOD
> configuration?

There was no intention to make a new era/modifier for this processing
(the input AOD/AODSIM is 940/940patch1).
Let's see what shows up in the pull requests to decide.

**Comment by arizzi** [comment]
@slava77 so if they have to modify modules that also run in reco you suggest to do it via cloning in top level miniaod cffs? Wouldn't this prevent the possibility of making more MiniAODV1?

**Comment by mbluj** [comment]
On Wed, Jan 24, 2018 at 2:02 PM, arizzi <notifications@github.com> wrote:

> @slava77 <https://github.com/slava77> so if they have to modify modules
> that also run in reco you suggest to do it via cloning in top level miniaod
> cffs?
>
It is exactly a way we want to proceed.

> Wouldn't this prevent the possibility of making more MiniAODV1?
>
Yes, it will prevent of making more MiniAODv1 with updated releases unless
a new Era is introduced. But do you expect such use case? Will it make
sense to produce MiniAODv1 with (current) releases designed for it?

**Comment by slava77** [comment]
On 1/24/18 5:02 AM, arizzi wrote:
> @slava77 <https://github.com/slava77> so if they have to modify modules
> that also run in reco you suggest to do it via cloning in top level
> miniaod cffs? Wouldn't this prevent the possibility of making more
> MiniAODV1?

Yes, it can prevent making new V1 requests if they have to be made in
the same release >9_4_3).
Is there a an actual long-term use case for miniAODv1?

**Comment by slava77** [comment]
@mbluj 
please clarify what is the future plan for tau.
If we keep the mainstream tau reco solely in AOD/RECO step, then I agree that making a modifier is more appropriate.
Which parts of tau reco and ID sequence are intended to be rerun in this reminiV2?
Is it the same that is remade for the legacy80X?
In this case it may be better to create a modifier (e.g. runTauInMiniAOD) so that it can be reused.
Anyways, I think that details can be discussed in the tau PR when it is made because the difference is a matter of about 10 lines of code change.

**Comment by mbluj** [comment]
On Wed, Jan 24, 2018 at 4:53 PM, Slava Krutelyov <notifications@github.com>
wrote:

> @mbluj <https://github.com/mbluj>
> please clarify what is the future plan for tau.
> If we keep the mainstream tau reco solely in AOD/RECO step, then I agree
> that making a modifier is more appropriate.
> Which parts of tau reco and ID sequence are intended to be rerun in this
> reminiV2?
> Is it the same that is remade for the legacy80X?
>
The minimal change is to run tau-Ids of the interest w/o underlying reco
part and basic discriminants. In this setup it is smaller than what is done
for legacy80X where reco part is run. However, the bigger setup consisting
reco can be also considered for simplicity (basically same as for legacy80X
which makes maintenance simpler) - please comment.

> In this case it may be better to create a modifier (e.g. runTauInMiniAOD)
> so that it can be reused.
> Anyways, I think that details can be discussed in the tau PR when it is
> made because the difference is a matter of about 10 lines of code change.
>
I agree.

Anyway, I hope be ready with the PR at some point tomorrow.

**Comment by slava77** [comment]
On 1/24/18 8:05 AM, mbluj wrote:
>> Which parts of tau reco and ID sequence are intended to be rerun in this
>> reminiV2?
>> Is it the same that is remade for the legacy80X?
>>
> The minimal change is to run tau-Ids of the interest w/o underlying reco
> part and basic discriminants. In this setup it is smaller than what is done
> for legacy80X where reco part is run. However, the bigger setup consisting
> reco can be also considered for simplicity (basically same as for legacy80X
> which makes maintenance simpler) - please comment.

I'd rather wait for that PR to comment.

**Comment by pablodecm** [comment]
@slava77 brief status update on DeepFlavour/TF backport: waiting for merging of https://github.com/cms-sw/cmsdist/pull/3689 and https://github.com/cms-sw/cmsdist/pull/3688, so they appear in the IBs to do the backport the PR. Could we do something to speed up those merges?

**Comment by slava77** [comment]
On 1/26/18 2:42 AM, Pablo de Castro wrote:
> @slava77 <https://github.com/slava77> brief status update on
> DeepFlavour/TF backport: waiting for merging of cms-sw/cmsdist#3689
> <https://github.com/cms-sw/cmsdist/pull/3689> and cms-sw/cmsdist#3688
> <https://github.com/cms-sw/cmsdist/pull/3688>, so they appear in the IBs
> to do the backport the PR. Could we do something to speed up those merges?
> 

Only https://github.com/cms-sw/cmsdist/pull/3688 is needed to test a
backport of DeepFlavour/TF .
This means that we can test the backport in jenkins when you make it.
(the setup of tests does not allow two cmsdist PRs to be tested together
with a cmssw PR).
So, I suggest that you test the backport in your local area with just a
copy of the files needed and submit it
and we will test it with 3688 to confirm the functionality.

**Comment by smuzaffar** [comment]
both  cms-sw/cmsdist#3689 and cms-sw/cmsdist#3688 are merged for next IB (23h00). As @slava77  mentioned , you only need cms-sw/cmsdist#3688 the PR

**Comment by slava77** [comment]
On 1/26/18 5:07 AM, Malik Shahzad Muzaffar wrote:
> both cms-sw/cmsdist#3689 <https://github.com/cms-sw/cmsdist/pull/3689>
> and cms-sw/cmsdist#3688 <https://github.com/cms-sw/cmsdist/pull/3688>
> are merged for next IB (23h00). As @slava77 <https://github.com/slava77>
> mentioned , you only need cms-sw/cmsdist#3688
> <https://github.com/cms-sw/cmsdist/pull/3688> the PR< /p>
> 

Shahzad, thank you for the quick response.

Pablo
, I'm looking forward for the PR.

**Comment by slava77** [comment]
It appears that the Jan 29 deadline is no more. Expect a confirmed updated target some time next week. This at best adds 1-2 weeks.

**Comment by mbluj** [comment]
A PR updating MVAIso tau-Ids has just been submitted #21977

**Comment by pablodecm** [comment]
@slava77 backport PR for DeepFlavour created at https://github.com/cms-sw/cmssw/pull/22042

**Comment by gpetruc** [comment]
Also #22125 is needed.

**Comment by arizzi** [comment]
for the records, we also have this to fix 
https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3572.html
(@gpetruc just reminded me)

**Comment by slava77** [comment]
On 2/6/18 4:09 AM, arizzi wrote:
> for the records, we also have this to fix
> https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3572.html
> (@gpetruc <https://github.com/gpetruc> just reminded me)
> 

please make a github issue for this, unless it's already tracked
somewhere (github or jira or alike)

**Comment by Sam-Harper** [comment]
just to add this to this issue: we need PRs:
https://github.com/cms-sw/cmssw/pull/22309 : enabling E/gamma IDs in miniAOD + scale & smearing corrections
https://github.com/cms-sw/cmssw/pull/22303 : electron MVA ID
https://github.com/cms-sw/cmssw/pull/22302 : rest of e/gamma IDs

for e/gamma

**Comment by lpernie** [comment]
GT with high level corrections PR#22381

**Comment by slava77** [comment]
I have updated the list of features submitted/requested for re-miniAOD v2 as of Mar 8 in the PR description.

**Comment by slava77** [comment]
the list of features was updated [see the issue description with check-boxes]

**Comment by fabiocos** [comment]
@slava77 after the integration of #22132 I understand that the list of RECO/analysis features needed for the reminiAODv2 94X has been exhausted, am I correct?
@arunhep @franzoni  #22638 implements the JEC, and this is the last input block needed for that reprocessing, correct? It should be forward ported into the master branch as well (it does not affect 2018, so its addition to 10_1_X is legitimate in my view)

**Comment by arunhep** [comment]
@fabiocos 

> #22638 implements the JEC, and this is the last input block needed for that reprocessing, correct? It should be forward ported into the master branch as well (it does not affect 2018, so its addition to 10_1_X is legitimate in my view)

from conditions, yes this is the last version. As i mentioned in my PR, I am porting these changes in 2017 MC workflows in master. PR for master will be opened today before afternoon.

**Comment by slava77** [comment]
updated on Mar 16. All PRs/features listed in "Features affecting miniAOD content" are now integrated in the MAOD branch.

**Comment by fabiocos** [comment]
@slava77 the last item on the list has been integrated, and 9_4_MAD_X is now empty

**Comment by slava77** [comment]
> @slava77 the last item on the list has been integrated, and 9_4_MAD_X is now empty

Thanks. I've updated the check-boxes.
It looks like we are done with integration.
I will close this issue once the production starts.

**Comment by slava77** [comment]
The production is on the way now.
Time to close the PR.
