### ISSUE TITLE
Features needed for CMSSW_10_1_2_patch2

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23021]
In view of the beginning of physics collision data taking, there has been a request of updating the production version of CMSSW_10_1_X with a fix in an Egamma producer needed by HLT. On top of that I see some  DQM request fully signed that corresponds to stuff already integrated since a while in master. The current list is:

- [ ] #22988 Fix for HLT Egamma producer
- [ ] #22952 Update of PixelActivityFilter

- [ ] #22960 online dead monitor channel
- [ ] #22971 fix digi reference size for summary plots
