### ISSUE TITLE
Features needed for CMSSW_10_1_5

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23192]
Following the discussion at the operations meeting of 11/5 https://indico.cern.ch/event/728960/  , a new CMSSW_10_1_5 is requested for the beginning of next week, with the following content:

- [x] #23170 updates to the EMTF unpacker to fix a crash at T0 (verified to be removed) and follow the firmware update (DQM offline plots would be zero, the code is reported to be already in production in online DQM); master version already integrated

- [x] #23064 backport of the tracking optimization for pixel FED 25, tested in CMSSW_10_2_0_pre2; as it changes a bit the physics content it will trigger a change in prompt reco version;

- [x] #23125 backport of a minor change in muon TriggerIdLoose, being tested in CMSSW_10_2_0_pre3

- [x] #22962 L1 DQM changes tested in CMSSW_10_2_0_pre2

- [x] #23040 L1 HCAL DQM changes, part of CMSSW_10_2_0_pre3, tested standone on 2018 data based on Configuration/DataProcessing

- [x] #23083 and #23097 online DQM changes already in CMSSW_10_2_0_pre3
