### ISSUE TITLE
Pending items to be addressed after the integration of the first part of the MTD tracking/geometry PR in CMSSW

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#24452]
The following issues raised during the review of #24285 were not addressed in that PR. The idea is to integrate now the large changes included in that pull request, so that development can continue more easily in the IBs. All the issue found  need to be fixed after that PR get merged in the CMSSW release, however.

- From https://github.com/cms-sw/cmssw/pull/24285#issuecomment-417234824:
   - Correct navigation by following the prescription of the Tracking POG and the outcome of the discussion in that forum

- From https://github.com/cms-sw/cmssw/pull/24285#issuecomment-417322262:
   - ```RecoMTD/DetLayers/src/MTDRingForwardDoubleLayer.cc```: refactor compatibleDets() code to common location (#24285 (comment))
   - ```RecoMTD/DetLayers/src/MTDRingForwardDoubleLayer.cc```: modernize ReferenceCountingPointer<BoundDisk> (#24285 (comment))
   - ```RecoMTD/Navigation/src/MTDNavigableLayer.cc``` etc.: make into a common class if no differences necessary for MTD usage (#24285 (comment))
   - ```DataFormats/FTLRecHit/src/FTLTrackingRecHit.cc```: extend trackerHitRTTI for this new class, rather than using typeid (#24285 (comment))
   - ```Geometry/MTDNumberingBuilder/interface/GeometricTimingDetExtra.h```: trailing underscore for data members (#24285 (comment))
   - ```Geometry/MTDNumberingBuilder/interface/CmsMTDStringToEnum.h```: trailing underscore for data members (#24285 (comment))

- From https://github.com/cms-sw/cmssw/pull/24285#issuecomment-418102225
  - Remove all duplicates and mirroring of the classes moved to ```TrackingTools/DetLayers```

@lgray @kpedro88 @VinInn @slava77 @ianna

**Comment by perrotta** [comment]
assign reconstruction, geometry

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
loginfo and RTTI items addressed by #25063

others remain to be addressed later

**Comment by kpedro88** [comment]
Here is the list of outstanding comments on #25063:
https://github.com/cms-sw/cmssw/pull/25063/files#r243429181
https://github.com/cms-sw/cmssw/pull/25063/files#r243420792
https://github.com/cms-sw/cmssw/pull/25063/files#r230146631
https://github.com/cms-sw/cmssw/pull/25063/files#r242384007
https://github.com/cms-sw/cmssw/pull/25063/files#r243436615
https://github.com/cms-sw/cmssw/pull/25063/files#r243435845
https://github.com/cms-sw/cmssw/pull/25063/files#r243436122
https://github.com/cms-sw/cmssw/pull/25063/files#r243436467
https://github.com/cms-sw/cmssw/pull/25063/files#r242387338
https://github.com/cms-sw/cmssw/pull/25063/files#r243436720
https://github.com/cms-sw/cmssw/pull/25063/files#r243437311
https://github.com/cms-sw/cmssw/pull/25063/files#r242416025
https://github.com/cms-sw/cmssw/pull/25063/files#r242416086
https://github.com/cms-sw/cmssw/pull/25063/files#r242418364
https://github.com/cms-sw/cmssw/pull/25063/files#r242418557
https://github.com/cms-sw/cmssw/pull/25063/files#r242423109
https://github.com/cms-sw/cmssw/pull/25063/files#r242420995
https://github.com/cms-sw/cmssw/pull/25063/files#r242423228
https://github.com/cms-sw/cmssw/pull/25063/files#r242423371
https://github.com/cms-sw/cmssw/pull/25063/files#r242423425
https://github.com/cms-sw/cmssw/pull/25063/files#r242423521
https://github.com/cms-sw/cmssw/pull/25063/files#r230149264
https://github.com/cms-sw/cmssw/pull/25063/files#r230150828
https://github.com/cms-sw/cmssw/pull/25063/files#r230149631
https://github.com/cms-sw/cmssw/pull/25063/files#r242424500
https://github.com/cms-sw/cmssw/pull/25063/files#r242673018
https://github.com/cms-sw/cmssw/pull/25063/files#r242679599
https://github.com/cms-sw/cmssw/pull/25063/files#r242750118
https://github.com/cms-sw/cmssw/pull/25063/files#r242368551
https://github.com/cms-sw/cmssw/pull/25063/files#r243138435
https://github.com/cms-sw/cmssw/pull/25063/files#r242371358

**Comment by ianna** [comment]
@fabiocos - please, check if there are any outstanding issues. Thanks!

**Comment by fabiocos** [comment]
@ianna @kpedro88 yes, I had kept this link in my folder to have a look at it, I will check for a cleaning when the basics of the ongoing PR are done

**Comment by fabiocos** [comment]
#32026 addresses some of the comments listed by @perrotta at the beginning of this issue in the ```Geometry``` and ```RecoMTD/DetLayers``` domains. There are two other issues there not managed for the time being:

- the refactorization of ```compatibleDets``` in the ```MTDRingForwardDoubleLayer``` class, with the problem being the same in the newly introduced ```MTDSectorForwardDoubleLayer``` class. Here honestly I wonder whether it is worthwhile to spend effort just to avoid having in two or three classes a similar loop of just a few lines, based on the example provided in the base class (but with a dummy implementation of ```groupedCompatibleDetsV```). One could think to move all the relevant code for the derived class method  inside a derived implementation of the dummy method, but I doubt this is really clean;

- I am not sure which kind of modernization of ReferenceCountingPointer is desired, may be getting rid of boost? In any case this goes well beyond MTD code, and it is a project in itself, unless I am misinterpreting the point.

Furthermore @ianna was suggesting to replace within ```MTDDetId``` data format ```enum``` with ```enum class```. This can be done, but it requires updates in a number of different places around the code, and the way I see it it would imply using ```static_cast``` within the boolean bit operations with masks, and as far as I can see there is no other such case within CMSSW. Before proposing such an update I'd like to be sure this is ok for other experts (@makortel any comment?)

**Comment by makortel** [comment]
In my opinion if the use of `enum class` leads to substantial use of `static_cast` to access the numerical value, it could be easier to stay with plain `enum`.

**Comment by perrotta** [comment]
Thank you @fabiocos,
Since in this issue there is also an action which relates to the RecoMuon code, before forgetting about it I provided a (trivial) fix with #32029

**Comment by fabiocos** [comment]
@makortel thanks for the comment, in operations like those implied by https://github.com/cms-sw/cmssw/blob/master/DataFormats/ForwardDetId/interface/BTLDetId.h#L76 an explicit type cast is required il ```enum class ``` is needed as far as I can see, just make a trivial test

```
12:37 mb-fc-03 534> cat testEnum.cpp 
#include <iostream>

int main() {

  enum pippo { aa = 1, bb = 2, cc = 3 };
  enum class ciccio : uint32_t { AA = 1, BB = 2, CC = 3 };

  const uint32_t mask = 0x2;

  std::cout << "Plain enum operation: " << (pippo::aa & mask) << " " << (pippo::bb & mask) << " " << (pippo::cc & mask) << std::endl;

  std::cout << "Class enum operation: " << (static_cast<uint32_t>(ciccio::AA) & mask) << " " << ((uint32_t)ciccio::BB & mask) << " " << (ciccio::CC & mask) << std::endl;

  return 0;

}
```

giving (on Mac with clang 11, but this is irrelevant here I believe)

```
12:41 mb-fc-03 535> g++ -std=c++11 testEnum.cpp 
testEnum.cpp:12:149: error: invalid operands to binary expression ('ciccio' and 'const uint32_t' (aka 'const unsigned int'))
  std::cout << "Class enum operation: " << (static_cast<uint32_t>(ciccio::AA) & mask) << " " << ((uint32_t)ciccio::BB & mask) << " " << (ciccio::CC & mask) << std::endl;
                                                                                                                                         ~~~~~~~~~~ ^ ~~~~
1 error generated.
```

**Comment by srimanob** [comment]
Hi @fabiocos
Would you mind summarising what still need to follow up with this ticket? Thanks very much.

**Comment by fabiocos** [comment]
@srimanob this issue is always in my inbox since 2018, I need to review with calm what possibly still applies as there were so many updates over time.

**Comment by fabiocos** [comment]
Pending list by @kpedro88 , partly addressed in #33680

- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r243429181
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r243420792
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r230146631
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242384007
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r243436615
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r243435845
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r243436122
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r243436467
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242387338
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r243436720
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r243437311
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242416025
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242416086
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242418364
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242418557
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242423109
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242420995
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242423228
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242423371
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242423425
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242423521
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r230149264
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r230150828
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r230149631
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242424500
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242673018
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242679599
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242750118
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242368551
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r243138435
- [ ] https://github.com/cms-sw/cmssw/pull/25063/files#r242371358
- [ ]

**Comment by fabiocos** [comment]
@srimanob as far as I can see, all the issues in the list by Kevin are addressed in #33680 .

**Comment by srimanob** [comment]
Thanks very much, @fabiocos 
When #33680 is merged, this issue can be closed.

**Comment by fabiocos** [comment]
@perrotta I believe that most of the original items of yours were already addressed, and for the few remaining https://github.com/cms-sw/cmssw/issues/24452#issuecomment-721844725 I already commented.

**Comment by perrotta** [comment]
> @perrotta I believe that most of the original items of yours were already addressed, and for the few remaining [#24452 (comment)](https://github.com/cms-sw/cmssw/issues/24452#issuecomment-721844725) I already commented.

Ok, thank you Fabio.

About "modernization of ReferenceCountingPointer", this was proposed by @lgray in the comment at L74 of RecoMTD/DetLayers/src/MTDRingForwardDoubleLayer.cc in #24285: I agree that this goes beyond the MTD domain, since it touches all tracking geometries in CMSSW.

**Comment by fabiocos** [comment]
Now that #33680 has been merged, I would consider this issue as basically solved, accounting for the comments above.

**Comment by perrotta** [comment]
+reconstruction
