### ISSUE TITLE
Features needed for NanoAOD processing in 10_2_X (December 2018)

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25425]
I want to document here the list of features (PRs) needed to build the next 10_2_X release to support nanoAOD processing. Looking at the present queue (status at 2018/12/13 09:45):

- [x] #25368 master nanoAOD code, to be updated to address #25409 

- [x] #25459 ECAL hot crystal filter 2017/2108

- [x] #25372 (with cms-sw/cmsdist#4518 ) it modifies miniAOD physics output (TO BE MERGED SECOND)

- [x] #25444 new modifiers for backward compatible management of code (TO BE MERGED FIRST)

@peruzzim @fgolf please confirm, integrate or amend this list
@slava77 @perrotta FYI

**Comment by fabiocos** [comment]
assign analysis

**Comment by peruzzim** [comment]
Further features that we were considering can be descoped to a later production, so we have no additions to the list.

Our view on the items:

- #25368: has been updated to address the validation workflow failure, now it seems to fail at merging. We will merge CMSSW_10_2_X in it as soon as #25372 is merged, fixing the conflict (we would not like to rebase because in this way it will merge back cleanly in our integration repository).
- #25226: the code will be activated in a future version, it's not needed now.
- #25372: our understanding is that it just adds new IDs without changing the content of the current ones, so we would deem it safe. Should a dedicated validation take place?

Let's not forget we also need cms-sw/cmsdist#4518.

**Comment by perrotta** [comment]
@fabiocos : about #25266 (you asked how it was validated):
- The code is "deactivated", and therefore it does not enter any workflow
- It has tested being able to run and produce some "reasonable" output with the recipe provided in https://github.com/cms-sw/cmssw/pull/25223#issuecomment-440283562
- The full validation of the physics content of newly added variables is responsability of the JetMET POG

**Comment by peruzzim** [comment]
Update: please take note, there is a minor change (adding one EGM ID to 2016 nanoAOD workflow, change only in nanoAOD configuration, not in the release) that we would like to add in a second moment, while the PdmV validation takes place.

cms-nanoAOD#272

**Comment by fabiocos** [comment]
@peruzzim @fgolf @prebello @zhenhu so far we are testing in the matrix NANO AODs for MC in some dedicated workflows

14:33 cmsdev15 2277> runTheMatrix.py -n | grep NANO
136.7722 RunJetHT2016H_nano+NANOEDM2016_80X+HARVESTNANOAOD2016_80X 
136.7952 RunJetHT2017C_94Xv2NanoAODINPUT+NANOEDM2017_94XMiniAODv2+HARVESTNANOAOD2017_94XMiniAODv2 
136.8521 RunJetHT2018A_nano+NANOEDM2018+HARVESTNANOAOD2018 
1325.6 TTbar_13_94Xv1NanoAODINPUT+NANOAODMC2017_94XMiniAODv1 
1325.7 TTbar_13_94Xv2NanoAODINPUT+NANOEDMMC2017_94XMiniAODv2+HARVESTNANOAODMC2017_94XMiniAODv2 
1325.8 TTbar_13_94Xv1NanoAODINPUT+NANOEDMMC2017_94XMiniAODv1+HARVESTNANOAODMC2017_94XMiniAODv1 
1325.9 TTbar_13_92XNanoAODINPUT+NANOEDMMC2017_92X+HARVESTNANOAODMC2017_92X 
1329.1 ZEE_13_80XNanoAODINPUT+NANOEDMMC2016_80X+HARVESTNANOAODMC2016_80X 
250200.118 ProdZEE_13UP18+DIGIPRMXUP18_PROD_PU25+RECOPRMXUP18PROD_PU25+NANOEDMMC2018_PROD 
250202.118 ProdTTbar_13UP18+DIGIPRMXUP18_PROD_PU25+RECOPRMXUP18PROD_PU25+NANOEDMMC2018_PROD 
250206.118 ProdZMM_13UP18+DIGIPRMXUP18_PROD_PU25+RECOPRMXUP18PROD_PU25+NANOEDMMC2018_PROD 

and in the regular 2018 MC RECO sequence. There are a few selected data tests (see the beginning of the previous list). I wonder whether it would not make sense at this point to have a NANO step also for the data workflows, as they are supposed to be now a regular part of the chain.

**Comment by peruzzim** [comment]
Another very small thing to be added, a filter bit from the backport of #25436

**Comment by peruzzim** [comment]
Status update (Dec 11th, 11am):

#25444 should be ready to merge (ops signature missing)
#25459 should be ready to merge (reco signature missing)
#25372 being tested after protecting miniAOD with modifier
#25368 will need fixing merging conflict when the other ones are merged + activating what is made available by the PR above

**Comment by peruzzim** [comment]
Status update:
#25444 merged
#25459 and #25372 signed, ready for final check and merge
#25368 will be fixed and tested after that (I have done already a private test in a local branch, it runs)

**Comment by peruzzim** [comment]
Status:

#25372 needs merging before #25368 can be modified and tested - anything preventing to move forward?

**Comment by fabiocos** [comment]
@peruzzim @fgolf the integration of #25372 for yesterday's 1100 IB failed for a couple of minutes, this caused some failures that have disappeared tonight. As anyway the update of master and 10_2_X for NanoAOD moved in different pieces, after the integration of the master version #25473 I have done a comparison between the 10_4_X and 10_2_X queues and see:

```
09:38 cmsdev15 2876> git diff CMSSW_10_4_X..remotes/official-cmssw/CMSSW_10_2_X -- PhysicsTools/NanoAOD
diff --git a/PhysicsTools/NanoAOD/plugins/BuildFile.xml b/PhysicsTools/NanoAOD/plugins/BuildFile.xml
index c2e6cf64bdd..f90f43e8434 100644
--- a/PhysicsTools/NanoAOD/plugins/BuildFile.xml
+++ b/PhysicsTools/NanoAOD/plugins/BuildFile.xml
@@ -5,7 +5,7 @@
 <use   name="FWCore/Utilities"/>
 <use   name="DataFormats/Candidate"/>
 <use   name="DataFormats/PatCandidates"/>
-<use   name="CommonTools/MVAUtils"/>
+<use   name="CommonTools/Utils"/>
 <use   name="RecoEgamma/EgammaTools"/>
 <use   name="PhysicsTools/JetMCUtils"/>
 <use   name="DataFormats/NanoAOD"/>
diff --git a/PhysicsTools/NanoAOD/python/nano_cff.py b/PhysicsTools/NanoAOD/python/nano_cff.py
index 0619d179d1f..9e4880dbb83 100644
--- a/PhysicsTools/NanoAOD/python/nano_cff.py
+++ b/PhysicsTools/NanoAOD/python/nano_cff.py
@@ -195,6 +195,7 @@ def nanoAOD_activateVID(process):
     process.electronSequence.insert(process.electronSequence.index(bitmapVIDForEle),process.egmGsfElectronIDSequence)
     for modifier in run2_miniAOD_80XLegacy, run2_nanoAOD_92X:
         modifier.toModify(process.electronMVAValueMapProducer, srcMiniAOD = "slimmedElectronsUpdated")
+        modifier.toModify(process.electronMVAVariableHelper, srcMiniAOD = "slimmedElectronsUpdated")
         modifier.toModify(process.egmGsfElectronIDs, physicsObjectSrc = "slimmedElectronsUpdated")
         if hasattr(process,"heepIDVarValueMaps"):
             modifier.toModify(process.heepIDVarValueMaps, elesMiniAOD = "slimmedElectronsUpdated")
```
```
09:46 cmsdev15 2878> git diff CMSSW_10_4_X..remotes/official-cmssw/CMSSW_10_2_X -- DataFormats/NanoAOD
diff --git a/DataFormats/NanoAOD/interface/MergeableCounterTable.h b/DataFormats/NanoAOD/interface/MergeableCounterTable.h
index 33295043435..cfd99d399b0 100644
--- a/DataFormats/NanoAOD/interface/MergeableCounterTable.h
+++ b/DataFormats/NanoAOD/interface/MergeableCounterTable.h
@@ -87,14 +87,7 @@ class MergeableCounterTable {
             if (!tryMerge(floatCols_, other.floatCols_)) return false;
             if (!tryMerge(vfloatCols_, other.vfloatCols_)) return false;
             return true; 
-        }
-
-        void swap(MergeableCounterTable& iOther) {
-          floatCols_.swap(iOther.floatCols_);
-          vfloatCols_.swap(iOther.vfloatCols_);
-          intCols_.swap(iOther.intCols_);
-          vintCols_.swap(iOther.vintCols_);
-        }
+         }
 
    private:
         std::vector<FloatColumn> floatCols_;
```

Is this intended?

**Comment by fabiocos** [comment]
@peruzzim @fgolf @prebello @zhenhu as a side note, the nanoAOD test should be likely extended to account for the configuration "run2_nanoAOD_102Xv1", I may imagine that this could become the new default for the tests on MC, and one data workflow corresponding to this scenario might be added (replacing the old 1325.9 recently removed)

**Comment by peruzzim** [comment]
The differences in `PhysicsTools/NanoAOD/plugins/BuildFile.xml` and `PhysicsTools/NanoAOD/python/nano_cff.py` look harmless, they are probably due to electronMVAVariableHelper being removed from electrons_cff.py but not from nano_cff.py. We will cross check that. @guitargeek 

The difference in `DataFormats/NanoAOD/interface/MergeableCounterTable.h` was introduced by #23776 that seems a general feature added to the master branch after it was branched out from 10_2_X.

**Comment by guitargeek** [comment]
Hi! The change in comes `PhysicsTools/NanoAOD/plugins/BuildFile.xml` from https://github.com/cms-sw/cmssw/pull/24432 and the one in `PhysicsTools/NanoAOD/python/nano_cff.py` from https://github.com/cms-sw/cmssw/pull/25337 with the removal of the ElectronMVAVariableHelper plugin. Both PRs validated to have no effect on the output.

**Comment by fabiocos** [comment]
Needs integrated in CMSSW_10_2_9 #25492
