### ISSUE TITLE
MTD code needed for the production version of 10_4_0 (mtd5)

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25712]
This issue is meant to keep track of the needed backports to 10_4_X from master needed for the production version of the MTD TDR release.

At present the following PRs should be considered in order of integration (22 January 22:45):

- [x] MTD geometry scenario D38 #25572 (10_5_X, merged) -> #25717 (10_4_X)

- [x] MTD time threshold #25644 (10_5_X, merged) -> #25716 (10_4_X)

- [x] MTD Fix to bar digitization #25635 (10_5_X, merged) -> #25714 (10_4_X)

- [x] MTD reco tuning #25636 (10_5_X, merged) -> #25715 (10_4_X)

- [x] MTD Time calibration #25634 (10_5_X, merged) -> #25713 (10_4_X)

- [x] MTD geometry scenario D39 #25639 (10_5_X, merged) -> #25728 (10_4_X)

- [x] 4D vertexing with MTD time + PID #25628 (10_5_X, merged) -> #25627 (10_4_X)

**Comment by fabiocos** [comment]
assign upgrade

@pmeridian @lgray @casarsa @bendavid FYI

**Comment by franzoni** [comment]
greetings @kpedro88 
all PR's and milestones reported in this issue are available and merged.
Is there any more step before we can have _mtd5 built ?

**Comment by kpedro88** [comment]
see #25765

**Comment by fabiocos** [comment]
Release built
