### ISSUE TITLE
Features for low pt electrons in B parking processing

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25991]
This issue is meant to keep track of the features needed to finalzie the low pt electron reconstruction at the heart of the B parking data reprocessing. As of now the list is (2019/03/05 17:00):

- [x] Basic low pt electrons up to GsfTracks: #25455 (master) -> #25680 (10_2_X)

- [x] Conversion from low pt GsfTracks: #25595 (master) -> #25761 (10_2_X)

- [x] Complete low pt electrons chain: #25753 (master) -> #25887 (10_2_X)

- [x] Link for LowPtGsf electrons: #26031 (master merged) -> #26036 (10_2_X)

- [x] Modify ValueMaps storing BDT output: #25915 (master merged) ; 
Fixes for low pt electrons: #25960 (master merged) ; 
Fix in SuperClusters: #25974 (master merged) ;
Very loose working point: #26012 (master merged)  } ->  #26013 (10_2_X)

- [x] BPHSkim and relval: #25892 (master merged);  #25984 (master merged); 
BPHSkim new working point: #26015 (master merged);
bParking era test workflows: #26035 (master merged) } -> #26038 (10_2_X)

**Comment by fabiocos** [comment]
@slava77 @perrotta @franzoni @srimanob FYI

**Comment by bainbrid** [comment]
@fabiocos many thanks for this. Some corrections/additions below:

__Reconstruction:__

- [ ] Basic low pt electrons up to GsfTracks: #25679 (10_5_X merged) -> #25680 (10_2_X merged)

- [ ] Complete low pt electrons chain: #25753 (10_5_X merged) -> #25887 (10_2_X merged)

- [ ] Modify ValueMaps storing BDT output: #25915 (10_5_X merged)  -> #25887 (10_2_X merged)

- [ ] Fixes for low pt electrons: #25960 (10_5_X merged) -> #25936 (10_2_X open)

- [ ] Fix in SuperClusters: #25974 (10_5_X merged) -> #25936 (10_2_X open)

__BDT models:__

- [ ] cms-data/RecoEgamma-ElectronIdentification#13 needed by #25936 (10_2_X open)

__Conversions and Skim:__

- [ ] Conversions from low pt GsfTracks: #25595 (10_5_X merged) -> #25761 (10_2_X merged)

- [ ] Skimming code: #25892 (10_5_X merged), #25984 (10_5_X open) -> back port PR for 10_2_X coming ASAP!

**Comment by perrotta** [comment]
@bainbrid , please correct either me or the table above, but the backport for #25915 is included in #25936 (yet to be merged), not  in #25887

**Comment by bainbrid** [comment]
@perrotta yes, good spot - thanks! Corrected.

**Comment by bainbrid** [comment]
FYI, we are considering to open two new PRs for the 10_2_X cycle:

1) an update of the ID BDT model in cms-data/RecoEgamma-ElectronIdentification, which involves a retraining follow the bug fixes in #25936. We could push this updated model to the current open PR (cms-data/RecoEgamma-ElectronIdentification#13) if people agree?

2) A switch to a new "Very Loose" working for the Seeding module. This would involve a 1-2 line change in a single configuration file. We will provide the physics case in tomorrow's RECO/AT meeting, along with an estimate of the computing cost. 

@gkaratha @mverzett

**Comment by bainbrid** [comment]
With regards to point 1) above, we now plan to proceed with the __existing__ ID model in Autumn18, as a recent retraining shows little improvement (and we will anyway further develop the ID on a longer timescale).

I've just made a new PR just made (#26012) which updates master to use the Autumn18 models, found in cms-data/RecoEgamma-ElectronIdentification#13. I've updated the status. This PR also uses a "Very Loose" working point in the low pT electron seed module for the bParking era. 

I will propagate the VL WP change back to the 10_2_X cycle, adding numbers for timing/footprint increases. I can either add it to the existing open #25936 or create a new PR. By default I will create a new PR, unless I hear otherwise.

**Comment by bainbrid** [comment]
The switch to a Very Loose working point for the bParking era is provided in #26012 (master) and the back port in #26013 (10_2_X). I've updated the status.

**Comment by bainbrid** [comment]
102X: #26013 (open) supersedes #25936 (closed)

**Comment by bainbrid** [comment]
Added "Change WP" (skimming code): #26015 (10_5_X open) -> #25995 (10_2_X open)

**Comment by bainbrid** [comment]
#26012 master merged. All PRs to master are now merged. 
There are two remaining open PRs to 10_2_X: #26013 and #25995.

**Comment by bainbrid** [comment]
FYI, we are planning one final PR (to master first, then back port), which will "link" each low pT GsfElectron (via its GsfTrack) to the corresponding "packedCandidate" or "lostTrack" using edm::Association containers. 

This is needed because the link between each GsfTrack and the corresponding "generalTrack" that seeds the low pT electron reconstruction is lost in the PAT framework. The above PR will provide this link for miniAOD and remove the need for (suboptimal) deltaR matching. 

@mverzett

**Comment by fabiocos** [comment]
@slava77 @perrotta following the discussion at the ORP, is the test of the B parking era performed by passing to cmsDriver the "--era Run2_2018,bParking" option? Could you please confirm or rectify in case?

**Comment by perrotta** [comment]
Exactly that one:
```
--era Run2_2018,bParking
```
One has to decide about the samples to use. I was thinking about modifying as such e.g. the workflows 136.85 (RunEGamma2018A) and a TTbar PU. @bainbrid suggested one signal sample instead for the MC workflow.

**Comment by bainbrid** [comment]
I think the suggested samples (RunEGamma2018A and TTbar) are also fine.

**Comment by prebello** [comment]
FYI @kfjack @zhenhu @pgunnell

**Comment by bainbrid** [comment]
#26013 merged to 10_2_X.

**Comment by bainbrid** [comment]
@fabiocos @slava77 @perrotta 

Here is an update.

Master:
* #26031 is a __new__ PR (GsfTracks<->PFCand linking) 

10_2_X:
* #26013 (reco) is merged into 10_2_X and will make an IB very soon
* #25995 (skimming) is open in 10_2_X and is pending signatures
* #26036  is a __new__ PR (the back port of #26031) 

Unless we have to iterate further with management on the skim working point, we believe the above PRs should complete our requirements for processing of the B Parked data set. 

Please can I query the timeline to form a new 10_2 release? Is it reasonable to hope for early next week? 

Our aim is to take this release and immediately process a "pilot run" comprising ~500M events.

**Comment by bainbrid** [comment]
#26031 merged to master

**Comment by prebello** [comment]
@fabiocos  please let us know which 10-2-X release will be prepared for early rereco bparking based in these PRs.
PdmV is waiting for it to reprocess the request from https://its.cern.ch/jira/browse/PDMVRERECO-12
Thank you

**Comment by fabiocos** [comment]
@prebello and I am waiting for PdmV to approve #26035, that will trigger the merge of #26038 that will contribute to next 10_2_X build :-)

**Comment by prebello** [comment]
@fabiocos  done
sorry I didn't reach it in time, before I asked you here, among my 1100 emails :-)

**Comment by bainbrid** [comment]
#26035 (master merged)

**Comment by perrotta** [comment]
This is just to remind here that there is still to solve (or at least to understand) the issue of tracks with all zero parameters, which was reported in https://github.com/cms-sw/cmssw/pull/26031#issuecomment-468902196
@bainbrid @mverzett : is there any progress on that front?

**Comment by bainbrid** [comment]
#26035 merged to master.
#26036 merged to CMSSW_10_2_X.

Only #26038 remains unmerged (to 10_2_X).

**Comment by fabiocos** [comment]
All the PRs discussed so far have been merged both in master and in 10_2_X (tonight IB will have them).
We still have the issue https://github.com/cms-sw/cmssw/issues/25991#issuecomment-469600672 to be clarified

**Comment by perrotta** [comment]
> Thanks all! We’ll get back to you on the warnings mentioned above. We’ve seen this before and believe it poses no problems. More details tomorrow. @perrotta, please can you provide exact details on how to reproduce the warnings?

It was explained in https://github.com/cms-sw/cmssw/pull/26031#issuecomment-468902196

Explicitely:
```
runTheMatrix.py -l 11024 --command "-n 60"
```
and the warnings show up in step3 at events 16, 24, 42, 59

**Comment by bainbrid** [comment]
#26038 merged into 10_2_X

**Comment by bainbrid** [comment]
All PRs are now merged and the full set are available in these two IBs:
- CMSSW_10_6_X_2019-03-05-1100
- CMSSW_10_2_X_2019-03-05-2300

Many thanks to everyone for helping us to get to this point!

**Comment by bainbrid** [comment]
@perrotta @fabio

With regards to the warnings mentioned here https://github.com/cms-sw/cmssw/pull/26031#issuecomment-468902196, we have seen these errors since early in the low pT electrons development cycle. The warnings arise in the ```PFTrackTransformer``` class, used by the ```PFElecTkProducer```. We make use of "utility methods" from this PF code that extrapolate (in this case) brem trajectories to the ECAL surface. These extrapolations are used to match bremsstrahlung radiation to ECAL deposits, which in turn are used to build the SuperClusters. The class has several logical clauses in which warnings are made when the extrapolation to the ECAL surface fails. 

We note that empirical observations indicate that these warnings are more prevalent in the low pT regime in which we are operating, and we are at or near some boundary conditions in terms of acceptance or performance of these PF algorithms. Any detailed investigations or changes to the PF code is outside the scope of this work and would likely incur a significant delay (weeks?). It was - and is - our intention to rely on this PF code "as is", so this is not a route we would like to pursue. (However, we will attempt to recreate the warnings now and - hopefully - isolate the details for these specific warning instances.)

We also note the following. 1) The warnings arise from a module that occurs after the production of the low pT GsfTracks, which are unaffected. 2) At worst, each warning simply implies a _potentially_ missing energy deposit from brem in the SuperCluster. While this is arguably not ideal, we note that the ID BDT is trained under these conditions. 3) Further, we rely heavily on the GsfTrack information for a P4 measurement; the SuperCluster is mainly used to strengthen the "ID" the electron, beyond that provided by the BDTs at the seeding step (that are quite discriminating already!).

Given this context, we would like to proceed and continue to a new 10_2_X release and the pilot run at the earliest opportunity, if you agree.

**Comment by perrotta** [comment]
@bainbrid : yes, the warnings themselves are there since longtime, and not only for the low pt electrons. The point that I asked to investigate is that in some of those warnings, the ones in correspondence of the events I listed, all the track parameters are identically 0! And this (apparently) happens only for the low pt electrons.
Could you please investigate where those tracks with 0 momentum and all other parameters come out? Then, once a track has pt=0 I am not surprised that it cannot reach the calos. The real issue is: "why a track with p=0 enters in your algo"?

> @perrotta @fabiocos
> 
> With regards to the warnings mentioned here [#26031 (comment)](https://github.com/cms-sw/cmssw/pull/26031#issuecomment-468902196), we have seen these errors since early in the low pT electrons development cycle. The warnings arise in the `PFTrackTransformer` class, used by the `PFElecTkProducer`. We make use of "utility methods" from this PF code that extrapolate (in this case) brem trajectories to the ECAL surface. These extrapolations are used to match bremsstrahlung radiation to ECAL deposits, which in turn are used to build the SuperClusters. The class has several logical clauses in which warnings are made when the extrapolation to the ECAL surface fails.
> 
> We note that empirical observations indicate that these warnings are more prevalent in the low pT regime in which we are operating, and we are at or near some boundary conditions in terms of acceptance or performance of these PF algorithms. Any detailed investigations or changes to the PF code is outside the scope of this work and would likely incur a significant delay (weeks?). It was - and is - our intention to rely on this PF code "as is", so this is not a route we would like to pursue. (However, we will attempt to recreate the warnings now and - hopefully - isolate the details for these specific warning instances.)
> 
> We also note the following. 1) The warnings arise from a module that occurs after the production of the low pT GsfTracks, which are unaffected. 2) At worst, each warning simply implies a _potentially_ missing energy deposit from brem in the SuperCluster. While this is arguably not ideal, we note that the ID BDT is trained under these conditions. 3) Further, we rely heavily on the GsfTrack information for a P4 measurement; the SuperCluster is mainly used to strengthen the "ID" the electron, beyond that provided by the BDTs at the seeding step (that are quite discriminating already!).
> 
> Given this context, we would like to proceed and continue to a new 10_2_X release and the pilot run at the earliest opportunity, if you agree.

**Comment by nancymarinelli** [comment]
@perrotta @mverzett @bainbrid I just submitted PR #26090 for the master, to include conversions from lowPtGsfTracks in miniAOD

**Comment by fabiocos** [comment]
All the code backported so far in 10_2_X will be included in the next release build, see #26098

**Comment by fabiocos** [comment]
@mverzett @bainbrid @nancymarinelli apart for possible fixes, is there anything else to be expected? Or we may finally consider this issue as finalized?

**Comment by bainbrid** [comment]
If @nancymarinelli is happy from the conversions side, then we are finished and can close. 

(The issue #26154 may potentially lead to some bug fixes ...)

**Comment by fabiocos** [comment]
I consider this plan of work as finalized.

**Comment by bainbrid** [comment]
For the record:

@prebello reports warnings/errors when running on data with EarlyReReco2018 conditions, found in this log ```/afs/cern.ch/user/p/prebello/public/forBparking/test.log```, as reported [here](https://its.cern.ch/jira/browse/PDMVRERECO-12). The command used is below:
```
cmsDriver.py RECO -s RAW2DIGI,L1Reco,RECO,SKIM:SkimBPark,EI,PAT,DQM:@allForPrompt --runUnscheduled --nThreads 8 --data --era Run2_2018,bParking --scenario pp --conditions 102X_dataRun2_Sep2018Rereco_v1 --eventcontent AOD,MINIAOD,DQM --datatier AOD,MINIAOD,DQMIO --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run2_2018,Configuration/DataProcessing/Utils.addMonitoring --filein /store/data/Run2018A/ParkingBPH1/RAW/v1/000/315/974/00000/8C4FF0AD-4D53-E811-ABFE-FA163EFF434D.root -n 1000 --python_filename=recoskim_Run2018A_ParkingBPH1.py --no_exec
```
The warnings/errors that appear to relate to the low pT electron code are listed below. 

Comments welcome. @mverzett @fabiocos @perrotta @Sam-Harper 

1)

``` 
%MSG-e PFTrackTransformer: PFElecTkProducer:lowPtGsfElePfGsfTracks 03-Apr-2019 01:24:36 CEST Run: 315974 Event: 44400197
BE CAREFUL: Gsf Tangents not stored in the event. You need to re-reco the particle-flow with RecoToDisplay_cfg.py and not RecoToDisplay_NoTracking_cfg.py
```

This error is produced [here](https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFTracking/src/PFTrackTransformer.cc#L787-L788). The message appears to be a little misleading, as the full reconstruction chain is performed in full in the same process and so the transient TrackExtra objects should be in memory. So the error is presumably related to the fact that the number of tangents is zero.  In the context of brem, this is presumably an issue as a brem should lead to a tangent. So perhaps this means that the electron did not brem? 

2)

```
%MSG-w OutOfBounds: LowPtGsfElectronSeedProducer:lowPtGsfElectronSeeds 03-Apr-2019 01:25:43 CEST Run: 315974 Event: 44589124
Prob Q outside the bounds of the quality word. Defaulting to Prob=0. Prob = 1 QualityWord = 960
```

This warning originates from the pixel RecHit code [here](https://github.com/cms-sw/cmssw/blob/master/DataFormats/TrackerRecHit2D/interface/SiPixelRecHitQuality.h#L135). I think [this](https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronSeedProducer.cc#L478) call on the [cloneSH](https://github.com/cms-sw/cmssw/blob/master/DataFormats/TrackerRecHit2D/interface/SiPixelRecHit.h#L45) on the SiPixcelRecHit class triggers the warning. 

3)

``` 
%MSG-w PFTrackTransformer: PFElecTkProducer:lowPtGsfElePfGsfTracks 03-Apr-2019 01:27:08 CEST Run: 315974 Event: 44558021
BREM Reco track charge = 0, type = 0, Pt = 0, P = 0
  R0 = 0 Z0 = 0
  number of tracker measurements = 0
  number of points total = 6
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = 4, Eta,Phi = 2.99906,0.941118, X,Y = 18.8814,25.9138, R,Z = 32.0629,320.9, E,Pt = 7.72584,0.75581
Traj point id = -1, layer = 5, Eta,Phi = 2.99918,0.941113, X,Y = 19.0197,26.1033, R,Z = 32.2976,323.287, E,Pt = 7.72584,0.75581
 PROPAGATION TO THE HCAL ENTRANCE HAS FAILED
%MSG
```

This warning is "understood" and has been discussed [here](https://github.com/cms-sw/cmssw/pull/26031#issuecomment-470933037) and later in the same thread. (Also discussed [here](https://github.com/cms-sw/cmssw/issues/25991#issuecomment-470057180).)

**Comment by perrotta** [comment]
Couldn't issue nr (2) be just due to some rounding effect?

Line https://github.com/cms-sw/cmssw/blob/master/DataFormats/TrackerRecHit2D/interface/SiPixelRecHitQuality.h#L134 says:
```C++
      if(prob<0 || prob>1) {
```
and the log reports that prob is equal to "1" (as a float)
