### ISSUE TITLE
Migrate Geometry packages to EventSetup consumes

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#26584]
This issue is to track the framework group's effort to migrate Geometry packages to EventSetup consumes (or, use them as guinea-pigs).

Below is a list of packages that use `ESHandle` or `ESTransientHandle` in an ESProducer. The ticked checkbox means that someone is already working on that package.

- [x] `Geometry/CSCGeometryBuilder` merged in #26566 
- [x] `Geometry/CaloEventSetup` merged in #26571 
- [x] `Geometry/DTGeometryBuilder` merged in #26577 
- [x] `Geometry/EcalAlgo` merged in #26585
- [x] `Geometry/EcalMapping` merged in #26580
- [x] `Geometry/EcalTestBeam` merged in #26581
- [x] `Geometry/GEMGeometryBuilder`merged in #26908
- [x] `Geometry/GlobalTrackingGeometryBuilder` merged in #26587
- [x] `Geometry/HGCalCommonData` merged in #26591
- [x] `Geometry/HGCalGeometry`merged in #26664
- [x] `Geometry/HcalCommonData`merged in #26671
- [x] `Geometry/HcalEventSetup` merged in #26707
- [x] `Geometry/HcalTowerAlgo` merged in #26733
- [x] `Geometry/MTDGeometryBuilder` merged in #26736
- [x] `Geometry/MTDNumberingBuilder` merged in #26734 
- [x] `Geometry/MuonNumbering` merged in #26706
- [x] `Geometry/RPCGeometryBuilder` merged in #26705
- [x] `Geometry/TrackerGeometryBuilder` merged in #26701
- [x] `Geometry/TrackerNumberingBuilder` merged in #26685
- [x] `Geometry/VeryForwardGeometryBuilder` merged in #26673

**Comment by Dr15Jones** [comment]
assign core

**Comment by makortel** [comment]
There is a conflicting PR modifying ESProducers in `Geometry/GEMGeometryBuilder` in https://github.com/cms-sw/cmssw/pull/26320.

**Comment by Dr15Jones** [comment]
@wddgit FYI

**Comment by makortel** [comment]
I should further note that the CaloEventSetup PR #26571 migrates the following files in other packages
- `Geometry/HGCalGeometry/plugins/moduleDB.cc`
- `Geometry/HcalEventSetup/src/moduleDB.cc`

because they contain specializations of the `CaloGeometryDBEP::produceAligned()` function. Therefore those files do not have to be migrated again in later PRs.

**Comment by Dr15Jones** [comment]
@makortel I've done both the MTD related packages

**Comment by makortel** [comment]
Thanks. So now we're only missing Geometry/GEMGeometryBuilder, for which it is probably best to wait for https://github.com/cms-sw/cmssw/pull/26320 to be merged.

**Comment by makortel** [comment]
The GEM PR #26320 got merged, but it's probably best to wait #26862 to get merged as well before trying out the simpler interface with the Geometry/GEMGeometryBuilder package.

**Comment by makortel** [comment]
#26862 got merged, I'll take care of Geometry/GEMGeometryBuilder.

**Comment by makortel** [comment]
> #26862 got merged, I'll take care of Geometry/GEMGeometryBuilder.

Done in #26908.

**Comment by makortel** [comment]
All related PRs have been merged, so this issue can be closed.
