### ISSUE TITLE
CMSSW_10_6_X finalization for UL and L1T TDR

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#26721]
This issue is meant to keep track of the needed CMSSW feature not yet integrated into the 10_6_X branch but still needed for either the UL processing or for the L1T TDR production.

The list of PRs is (updated at 2019-05-13 10:20):

- [x] #26302 (MET uncertainties)

- [ ] #26486 (Adapting VID & Nano to the new E/gamma UL format + adding HEEP V7.1)

- [x] #26607 ([PPS] Timing detectors tracks window reduced to 25 ns in lite tracks format)

- [x] #26679 (Restore fed error treatment for phase0v2)

- [x] #26672 (define nano 2018 _102Xv1 steps and use in 2018 data nano wf 136.8521)

- [x] #26703 (NanoAOD developments: 190508 version, part 1 for UL)

- [x] #26704 (sim hit info addition for MiniAOD)

- [x] #26723 (Fix in preselection of low pt muon mva)

- [x] #26739 (PPS: bugfix in proton reconstruction)

On top of this, according to the reports we should expect:

- Update to the high pt muons reconstruction @Fedespring @drkovalskyi

- Update to the EGamma calibration code @Sam-Harper 

- Possible fix for problems reported in the CMSSW_10_6_0_pre4 phase2 RelVal validation (failure in DQMIO merge @fioriNTU @schneiml @andrius-k)

- Additional updates to NANO not related to 102X @peruzzim @fgolf 

Please comment about possible further additions

**Comment by fabiocos** [comment]
@slava77 @perrotta FYI

**Comment by drkovalskyi** [comment]
For muons:

- #26704 sim hit info addition for MiniAOD
- #26723 Fix in preselection of low pt muon mva

We may have one more PR for DYT depending on the outcome of the ongoing validation

**Comment by kpedro88** [comment]
I am meeting with @kdlong next Monday to discuss improving the organization of generator weights. This is rather late to be ready for 10_6_0, but would be a boon for analysis users.

**Comment by slava77** [comment]
> For muons:
> 
>     * #26704 sim hit info addition for MiniAOD
> 
>     * #26723 Fix in preselection of low pt muon mva
> 
> 
> We may have one more PR for DYT depending on the outcome of the ongoing validation

these are now signed by reco.

**Comment by slava77** [comment]
> The list of PRs is (updated at 2019-05-09):
> 
>     * [ ]  #26302 (MET uncertainties)
> 
>     * [ ]  #26607 ([PPS] Timing detectors tracks window reduced to 25 ns in lite tracks format)
> 
>     * [ ]  #26672 (define nano 2018 _102Xv1 steps and use in 2018 data nano wf 136.8521)

these are fully signed and are ready to be merged

**Comment by fabiocos** [comment]
@slava77 @drkovalskyi thank you, I will merge tonight whatever signed already in the list and update it accordingly

**Comment by srimanob** [comment]
@mverzett, if you open a PR on new HLT dataformat for BTV, please mention here also. Thx.

**Comment by Sam-Harper** [comment]
This is the PR for the supercluster regression
https://github.com/cms-sw/cmssw/pull/26763

The electron/photon regression is about 1-2 weeks away as per the agreed schedule with PPD. The ele/pho regression can be applied on the miniAOD though. 

The PF cluster regression (no PR expected, just GT change) is in progress.

**Comment by drkovalskyi** [comment]
DYT PR #26778 
There should be nothing else pending from Muon POG.

**Comment by fabiocos** [comment]
Post-10_6_0 pending items according to reports:

- [ ]  #26486 (Adapting VID & Nano to the new E/gamma UL format + adding HEEP V7.1)

- [ ] #26763 (updating SC ref corrector for UL regression)

- [ ] #26778 DyT v2 on up to eta 1p2

**Comment by srimanob** [comment]
- [ ] https://github.com/cms-sw/cmssw/pull/26785 (Updating the skim for Run-2 ULs)

**Comment by peruzzim** [comment]
- [ ] #26724 Higgs STXS Stage 1.1

**Comment by fabiocos** [comment]
I close this issue, and move the list of residual needs for 10_6_1 to #26832
