### ISSUE TITLE
Post 10_6_0 UL and L1T TDR updates

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#26832]
This issues is the follow-up of #26721 after CMSSW_10_6_0 has been built, and it aims to collect the list of late developments and urgent fixes integrated in 11_0_X and backported into 10_6_X, targeting the 10_6_1 build. The list available so far is (2019-05-21, 11:00):

- [x] Adapting VID & Nano to the new E/gamma UL format + adding HEEP V7.1, #26486 (11_0_X merged) -> #26786 (10_6_X)

- [x] updating SC reg corrector for UL regression, #26763 (11_0_X merged) -> #26797 (10_6_X)

- [x] DyT v2 on up to eta 1p2, #26778 (11_0_X merged) -> #26827 (10_6_X)

- [x] Update triggers for Run2 monopole analysis, #26785 (11_0_X merged) -> #26826 (10_6_X)

- [x] Higgs STXS Stage 1.1, #26724 (11_0_X) -> (10_6_X)

- [x] NANOAOD updates from XPOG, #26844 (11_0_X) -> #26845 (10_6_X)

Other PRs have already a backport available in 10_6_X

**Comment by peruzzim** [comment]
- [ ] NANOAOD updates from XPOG, #26844 (11_0_X) -> #26845 (10_6_X)

**Comment by slava77** [comment]
a backport of #26824 will be requested for 10_6_1 as well
@mbluj

**Comment by mbluj** [comment]
> a backport of #26824 will be requested for 10_6_1 as well
> @mbluj
PR #26859 prepared.

**Comment by fabiocos** [comment]
Every listed PR has been merged. More known developments from EGM group will be followed through the usual review/ORP path
