### ISSUE TITLE
NanoAODv6 release preparation

### ISSUE THREAD

**Issue by peruzzim** [cms-sw/cmssw#28119]
This is to collect and track items for integration in the release for NanoAODv6:

- [x] #28096 Enable pt-dependent JER-SF and phi-dependent JEC application in PAT
- [x] #28118 Muon FSR recovery for miniaod and nanoaod
- [x] #28122 NanoAODv6 updates, part 2
- [x] #28196 NanoAODv6, config fixes for UL
- [x] #28221 Fix electron PFCandidates RefVector usage in MuonFSRProducer

**Comment by peruzzim** [comment]
assign xpog

**Comment by peruzzim** [comment]
Branches for a cumulative backport of #28103 and #28122 are also ready:

https://github.com/cms-sw/cmssw/compare/CMSSW_10_2_X...cms-nanoAOD:pr_nanov6_102X
https://github.com/cms-sw/cmssw/compare/CMSSW_10_6_X...cms-nanoAOD:pr_nanov6_106X

and will depend on backports of #28096 (PRs open) and #28118 (PRs not open yet)

**Comment by peruzzim** [comment]
I'm afraid we forgot to update NanoAOD code for the backports of #27184, would like to check with @ahinzmann @lathomas before building _pre10

**Comment by peruzzim** [comment]
the jet ID is now updated in #28122

**Comment by peruzzim** [comment]
everything is now merged to build _pre10 from the xpog side
discussion on backport preparation will follow

**Comment by peruzzim** [comment]
List of features to be backported to 10_2_X for NanoAODv6:

- [ ] #28095 Backport jetid updates to 102X
- [ ] #28098 Enable pt-dependent JER-SF and phi-dependent JEC application in PAT [102X backport]
- [ ] #28135 Muon FSR recovery for miniaod and nanoaod [102X]
- [ ] #28145 NanoAODv6 updates [102X]

#28145 depends technically only on #28095 and #28135, but we will need also #28098 to use the intended jet energy corrections.

**Comment by peruzzim** [comment]
Status update:

- 11_0_0_pre10 is built with the updates merged and should be used for validation
- I have tested the backport to 102X, it runs and gives changes where expected, so I signed it

@srimanob @ameyer-cern

**Comment by peruzzim** [comment]
RelVals have run, we can build the 10_2_X release for NanoAODv6 productioncampaign.
Please refer above for the list of pull requests to be merged (the last fix #28221 that has also been included and tested in the backport).
It's not needed to build a new 11_0_X, nor a new 10_6_X - actually, for these we should wait for the backport of #28196 that does nothing on the samples supported by 10_2_X and therefore is not needed in the 10_2_X release.

**Comment by srimanob** [comment]
Hi,
What about https://github.com/cms-sw/cmssw/pull/28221 
?

**Comment by srimanob** [comment]
Hi @peruzzim @fabiocos 
So, all we need are merged already, right?
It's a matter to build after few stable IB, correct?

**Comment by fabiocos** [comment]
@srimanob no, I've just merged the fix #28221, and this was holding the integration of the remaining pieces in 10_2_X. As soon those are signed I may merge and build the release, provided there is no surprise in the IB

**Comment by peruzzim** [comment]
For 10_6_X to be used in UL, we need:
- [x] #28094 Backport jetid updates #27184 #27691 to 106X
- [x] #28136 Muon FSR recovery for miniaod and nanoaod [106X]
- [ ] #28097 Enable pt-dependent JER-SF and phi-dependent JEC application in PAT [106X backport
- [ ] #28182 NanoAODv6 updates [106X] (includes backport of #28196)

I don't understand the role of #28177 - is that just for validation activities i.e. is the title misleading?

**Comment by fabiocos** [comment]
@aspiezia should comment, I agree that the title should be better updated to reflect the Validation nature of that update

**Comment by aspiezia** [comment]
Dear All, I have updated the title to "Tau Validation/DQM: switching deepTau version from v2 to v2p1 for CMSSW10_6_X".
Please let me know if that makes sense to you.

**Comment by fabiocos** [comment]
@peruzzim as discussed, for the record: the integration of #28182 in 10_6_X causes two test workflows to fail (11824 and 11825):

```
----- Begin Fatal Exception 29-Oct-2019 03:09:54 CET-----------------------
An exception of category 'Key not found' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 1
   [1] Running path 'nanoAOD_step'
   [2] Calling method for module PATTauRefSelector/'finalTaus'
Exception Message:
pat::Tau: the ID byVVVLooseDeepTau2017v2p1VSjet can't be found in this pat::Tau.
The available IDs are: 'againstElectronLooseMVA6' 'againstElectronMVA6Raw' 'againstElectronMVA6category' 'againstElectronMediumMVA6' 'againstElectronTightMVA6' 'againstElectronVLooseMVA6' 'againstElectronVTightMVA6' 'againstMuonLoose3' 'againstMuonTight3' 'byCombinedIsolationDeltaBetaCorrRaw3Hits' 'byIsolationMVArun2v1DBdR03oldDMwLTraw' 'byIsolationMVArun2v1DBnewDMwLTraw' 'byIsolationMVArun2v1DBoldDMwLTraw' 'byIsolationMVArun2v1PWdR03oldDMwLTraw' 'byIsolationMVArun2v1PWnewDMwLTraw' 'byIsolationMVArun2v1PWoldDMwLTraw' 'byLooseCombinedIsolationDeltaBetaCorr3Hits' 'byLooseIsolationMVArun2v1DBdR03oldDMwLT' 'byLooseIsolationMVArun2v1DBnewDMwLT' 'byLooseIsolationMVArun2v1DBoldDMwLT' 'byLooseIsolationMVArun2v1PWdR03oldDMwLT' 'byLooseIsolationMVArun2v1PWnewDMwLT' 'byLooseIsolationMVArun2v1PWoldDMwLT' 'byMediumCombinedIsolationDeltaBetaCorr3Hits' 'byMediumIsolationMVArun2v1DBdR03oldDMwLT' 'byMediumIsolationMVArun2v1DBnewDMwLT' 'byMediumIsolationMVArun2v1DBoldDMwLT' 'byMediumIsolationMVArun2v1PWdR03oldDMwLT' 'byMediumIsolationMVArun2v1PWnewDMwLT' 'byMediumIsolationMVArun2v1PWoldDMwLT' 'byPhotonPtSumOutsideSignalCone' 'byTightCombinedIsolationDeltaBetaCorr3Hits' 'byTightIsolationMVArun2v1DBdR03oldDMwLT' 'byTightIsolationMVArun2v1DBnewDMwLT' 'byTightIsolationMVArun2v1DBoldDMwLT' 'byTightIsolationMVArun2v1PWdR03oldDMwLT' 'byTightIsolationMVArun2v1PWnewDMwLT' 'byTightIsolationMVArun2v1PWoldDMwLT' 'byVLooseIsolationMVArun2v1DBdR03oldDMwLT' 'byVLooseIsolationMVArun2v1DBnewDMwLT' 'byVLooseIsolationMVArun2v1DBoldDMwLT' 'byVLooseIsolationMVArun2v1PWdR03oldDMwLT' 'byVLooseIsolationMVArun2v1PWnewDMwLT' 'byVLooseIsolationMVArun2v1PWoldDMwLT' 'byVTightIsolationMVArun2v1DBdR03oldDMwLT' 'byVTightIsolationMVArun2v1DBnewDMwLT' 'byVTightIsolationMVArun2v1DBoldDMwLT' 'byVTightIsolationMVArun2v1PWdR03oldDMwLT' 'byVTightIsolationMVArun2v1PWnewDMwLT' 'byVTightIsolationMVArun2v1PWoldDMwLT' 'byVVLooseIsolationMVArun2v1DBdR03oldDMwLT' 'byVVLooseIsolationMVArun2v1DBnewDMwLT' 'byVVLooseIsolationMVArun2v1DBoldDMwLT' 'byVVTightIsolationMVArun2v1DBdR03oldDMwLT' 'byVVTightIsolationMVArun2v1DBnewDMwLT' 'byVVTightIsolationMVArun2v1DBoldDMwLT' 'byVVTightIsolationMVArun2v1PWdR03oldDMwLT' 'byVVTightIsolationMVArun2v1PWnewDMwLT' 'byVVTightIsolationMVArun2v1PWoldDMwLT' 'chargedIsoPtSum' 'chargedIsoPtSumdR03' 'decayModeFinding' 'decayModeFindingNewDMs' 'footprintCorrection' 'footprintCorrectiondR03' 'neutralIsoPtSum' 'neutralIsoPtSumWeight' 'neutralIsoPtSumWeightdR03' 'neutralIsoPtSumdR03' 'photonPtSumOutsideSignalCone' 'photonPtSumOutsideSignalConedR03' 'puCorrPtSum' 'byDeepTau2017v2VSeraw' 'byDeepTau2017v2VSjetraw' 'byDeepTau2017v2VSmuraw' 'byLooseDeepTau2017v2VSe' 'byLooseDeepTau2017v2VSjet' 'byLooseDeepTau2017v2VSmu' 'byMediumDeepTau2017v2VSe' 'byMediumDeepTau2017v2VSjet' 'byMediumDeepTau2017v2VSmu' 'byTightDeepTau2017v2VSe' 'byTightDeepTau2017v2VSjet' 'byTightDeepTau2017v2VSmu' 'byVLooseDeepTau2017v2VSe' 'byVLooseDeepTau2017v2VSjet' 'byVLooseDeepTau2017v2VSmu' 'byVTightDeepTau2017v2VSe' 'byVTightDeepTau2017v2VSjet' 'byVVLooseDeepTau2017v2VSe' 'byVVLooseDeepTau2017v2VSjet' 'byVVTightDeepTau2017v2VSe' 'byVVTightDeepTau2017v2VSjet' 'byVVVLooseDeepTau2017v2VSe' 'byVVVLooseDeepTau2017v2VSjet' 'againstElectronLooseMVA62018' 'againstElectronMVA6Raw2018' 'againstElectronMVA6category2018' 'againstElectronMediumMVA62018' 'againstElectronTightMVA62018' 'againstElectronVLooseMVA62018' 'againstElectronVTightMVA62018' 'byIsolationMVArun2v1DBdR03oldDMwLTraw2017v2' 'byIsolationMVArun2v1DBnewDMwLTraw2017v2' 'byIsolationMVArun2v1DBoldDMwLTraw2015' 'byIsolationMVArun2v1DBoldDMwLTraw2017v2' 'byLooseIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byLooseIsolationMVArun2v1DBnewDMwLT2017v2' 'byLooseIsolationMVArun2v1DBoldDMwLT2015' 'byLooseIsolationMVArun2v1DBoldDMwLT2017v2' 'byMediumIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byMediumIsolationMVArun2v1DBnewDMwLT2017v2' 'byMediumIsolationMVArun2v1DBoldDMwLT2015' 'byMediumIsolationMVArun2v1DBoldDMwLT2017v2' 'byTightIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byTightIsolationMVArun2v1DBnewDMwLT2017v2' 'byTightIsolationMVArun2v1DBoldDMwLT2015' 'byTightIsolationMVArun2v1DBoldDMwLT2017v2' 'byVLooseIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVLooseIsolationMVArun2v1DBnewDMwLT2017v2' 'byVLooseIsolationMVArun2v1DBoldDMwLT2015' 'byVLooseIsolationMVArun2v1DBoldDMwLT2017v2' 'byVTightIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVTightIsolationMVArun2v1DBnewDMwLT2017v2' 'byVTightIsolationMVArun2v1DBoldDMwLT2015' 'byVTightIsolationMVArun2v1DBoldDMwLT2017v2' 'byVVLooseIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVVLooseIsolationMVArun2v1DBnewDMwLT2017v2' 'byVVLooseIsolationMVArun2v1DBoldDMwLT2017v2' 'byVVTightIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVVTightIsolationMVArun2v1DBnewDMwLT2017v2' 'byVVTightIsolationMVArun2v1DBoldDMwLT2015' 'byVVTightIsolationMVArun2v1DBoldDMwLT2017v2' .
----- End Fatal Exception -------------------------------------------------
```

**Comment by peruzzim** [comment]
relval workflows are fixed in recent 10_6_X integration builds by #28302, that is specific for the 10_6_X configuration and does not need being ported elsewhere

**Comment by peruzzim** [comment]
+xpog

I think we can close the NanoAODv6 chapter, as pull requests are merged in all branches:
- 10_2_X: integrated in CMSSW_10_2_18 (being used for the production campaign)
- 10_6_X: merged, release not yet built
- 11_0_X: integrated in CMSSW_11_0_0_pre11

**Comment by alkaloge** [comment]
> @peruzzim as discussed, for the record: the integration of #28182 in 10_6_X causes two test workflows to fail (11824 and 11825):
> 
> ```
> ----- Begin Fatal Exception 29-Oct-2019 03:09:54 CET-----------------------
> An exception of category 'Key not found' occurred while
>    [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 1
>    [1] Running path 'nanoAOD_step'
>    [2] Calling method for module PATTauRefSelector/'finalTaus'
> Exception Message:
> pat::Tau: the ID byVVVLooseDeepTau2017v2p1VSjet can't be found in this pat::Tau.
> The available IDs are: 'againstElectronLooseMVA6' 'againstElectronMVA6Raw' 'againstElectronMVA6category' 'againstElectronMediumMVA6' 'againstElectronTightMVA6' 'againstElectronVLooseMVA6' 'againstElectronVTightMVA6' 'againstMuonLoose3' 'againstMuonTight3' 'byCombinedIsolationDeltaBetaCorrRaw3Hits' 'byIsolationMVArun2v1DBdR03oldDMwLTraw' 'byIsolationMVArun2v1DBnewDMwLTraw' 'byIsolationMVArun2v1DBoldDMwLTraw' 'byIsolationMVArun2v1PWdR03oldDMwLTraw' 'byIsolationMVArun2v1PWnewDMwLTraw' 'byIsolationMVArun2v1PWoldDMwLTraw' 'byLooseCombinedIsolationDeltaBetaCorr3Hits' 'byLooseIsolationMVArun2v1DBdR03oldDMwLT' 'byLooseIsolationMVArun2v1DBnewDMwLT' 'byLooseIsolationMVArun2v1DBoldDMwLT' 'byLooseIsolationMVArun2v1PWdR03oldDMwLT' 'byLooseIsolationMVArun2v1PWnewDMwLT' 'byLooseIsolationMVArun2v1PWoldDMwLT' 'byMediumCombinedIsolationDeltaBetaCorr3Hits' 'byMediumIsolationMVArun2v1DBdR03oldDMwLT' 'byMediumIsolationMVArun2v1DBnewDMwLT' 'byMediumIsolationMVArun2v1DBoldDMwLT' 'byMediumIsolationMVArun2v1PWdR03oldDMwLT' 'byMediumIsolationMVArun2v1PWnewDMwLT' 'byMediumIsolationMVArun2v1PWoldDMwLT' 'byPhotonPtSumOutsideSignalCone' 'byTightCombinedIsolationDeltaBetaCorr3Hits' 'byTightIsolationMVArun2v1DBdR03oldDMwLT' 'byTightIsolationMVArun2v1DBnewDMwLT' 'byTightIsolationMVArun2v1DBoldDMwLT' 'byTightIsolationMVArun2v1PWdR03oldDMwLT' 'byTightIsolationMVArun2v1PWnewDMwLT' 'byTightIsolationMVArun2v1PWoldDMwLT' 'byVLooseIsolationMVArun2v1DBdR03oldDMwLT' 'byVLooseIsolationMVArun2v1DBnewDMwLT' 'byVLooseIsolationMVArun2v1DBoldDMwLT' 'byVLooseIsolationMVArun2v1PWdR03oldDMwLT' 'byVLooseIsolationMVArun2v1PWnewDMwLT' 'byVLooseIsolationMVArun2v1PWoldDMwLT' 'byVTightIsolationMVArun2v1DBdR03oldDMwLT' 'byVTightIsolationMVArun2v1DBnewDMwLT' 'byVTightIsolationMVArun2v1DBoldDMwLT' 'byVTightIsolationMVArun2v1PWdR03oldDMwLT' 'byVTightIsolationMVArun2v1PWnewDMwLT' 'byVTightIsolationMVArun2v1PWoldDMwLT' 'byVVLooseIsolationMVArun2v1DBdR03oldDMwLT' 'byVVLooseIsolationMVArun2v1DBnewDMwLT' 'byVVLooseIsolationMVArun2v1DBoldDMwLT' 'byVVTightIsolationMVArun2v1DBdR03oldDMwLT' 'byVVTightIsolationMVArun2v1DBnewDMwLT' 'byVVTightIsolationMVArun2v1DBoldDMwLT' 'byVVTightIsolationMVArun2v1PWdR03oldDMwLT' 'byVVTightIsolationMVArun2v1PWnewDMwLT' 'byVVTightIsolationMVArun2v1PWoldDMwLT' 'chargedIsoPtSum' 'chargedIsoPtSumdR03' 'decayModeFinding' 'decayModeFindingNewDMs' 'footprintCorrection' 'footprintCorrectiondR03' 'neutralIsoPtSum' 'neutralIsoPtSumWeight' 'neutralIsoPtSumWeightdR03' 'neutralIsoPtSumdR03' 'photonPtSumOutsideSignalCone' 'photonPtSumOutsideSignalConedR03' 'puCorrPtSum' 'byDeepTau2017v2VSeraw' 'byDeepTau2017v2VSjetraw' 'byDeepTau2017v2VSmuraw' 'byLooseDeepTau2017v2VSe' 'byLooseDeepTau2017v2VSjet' 'byLooseDeepTau2017v2VSmu' 'byMediumDeepTau2017v2VSe' 'byMediumDeepTau2017v2VSjet' 'byMediumDeepTau2017v2VSmu' 'byTightDeepTau2017v2VSe' 'byTightDeepTau2017v2VSjet' 'byTightDeepTau2017v2VSmu' 'byVLooseDeepTau2017v2VSe' 'byVLooseDeepTau2017v2VSjet' 'byVLooseDeepTau2017v2VSmu' 'byVTightDeepTau2017v2VSe' 'byVTightDeepTau2017v2VSjet' 'byVVLooseDeepTau2017v2VSe' 'byVVLooseDeepTau2017v2VSjet' 'byVVTightDeepTau2017v2VSe' 'byVVTightDeepTau2017v2VSjet' 'byVVVLooseDeepTau2017v2VSe' 'byVVVLooseDeepTau2017v2VSjet' 'againstElectronLooseMVA62018' 'againstElectronMVA6Raw2018' 'againstElectronMVA6category2018' 'againstElectronMediumMVA62018' 'againstElectronTightMVA62018' 'againstElectronVLooseMVA62018' 'againstElectronVTightMVA62018' 'byIsolationMVArun2v1DBdR03oldDMwLTraw2017v2' 'byIsolationMVArun2v1DBnewDMwLTraw2017v2' 'byIsolationMVArun2v1DBoldDMwLTraw2015' 'byIsolationMVArun2v1DBoldDMwLTraw2017v2' 'byLooseIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byLooseIsolationMVArun2v1DBnewDMwLT2017v2' 'byLooseIsolationMVArun2v1DBoldDMwLT2015' 'byLooseIsolationMVArun2v1DBoldDMwLT2017v2' 'byMediumIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byMediumIsolationMVArun2v1DBnewDMwLT2017v2' 'byMediumIsolationMVArun2v1DBoldDMwLT2015' 'byMediumIsolationMVArun2v1DBoldDMwLT2017v2' 'byTightIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byTightIsolationMVArun2v1DBnewDMwLT2017v2' 'byTightIsolationMVArun2v1DBoldDMwLT2015' 'byTightIsolationMVArun2v1DBoldDMwLT2017v2' 'byVLooseIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVLooseIsolationMVArun2v1DBnewDMwLT2017v2' 'byVLooseIsolationMVArun2v1DBoldDMwLT2015' 'byVLooseIsolationMVArun2v1DBoldDMwLT2017v2' 'byVTightIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVTightIsolationMVArun2v1DBnewDMwLT2017v2' 'byVTightIsolationMVArun2v1DBoldDMwLT2015' 'byVTightIsolationMVArun2v1DBoldDMwLT2017v2' 'byVVLooseIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVVLooseIsolationMVArun2v1DBnewDMwLT2017v2' 'byVVLooseIsolationMVArun2v1DBoldDMwLT2017v2' 'byVVTightIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVVTightIsolationMVArun2v1DBnewDMwLT2017v2' 'byVVTightIsolationMVArun2v1DBoldDMwLT2015' 'byVVTightIsolationMVArun2v1DBoldDMwLT2017v2' .
> ----- End Fatal Exception -------------------------------------------------
> ```
@mariadalfonso @gouskos @fabiocos @peruzzim
The problem is still there in 10_6_5, deepTau iDs are still not available

**Comment by alkaloge** [comment]
> > @peruzzim as discussed, for the record: the integration of #28182 in 10_6_X causes two test workflows to fail (11824 and 11825):
> > ```
> > ----- Begin Fatal Exception 29-Oct-2019 03:09:54 CET-----------------------
> > An exception of category 'Key not found' occurred while
> >    [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 1
> >    [1] Running path 'nanoAOD_step'
> >    [2] Calling method for module PATTauRefSelector/'finalTaus'
> > Exception Message:
> > pat::Tau: the ID byVVVLooseDeepTau2017v2p1VSjet can't be found in this pat::Tau.
> > The available IDs are: 'againstElectronLooseMVA6' 'againstElectronMVA6Raw' 'againstElectronMVA6category' 'againstElectronMediumMVA6' 'againstElectronTightMVA6' 'againstElectronVLooseMVA6' 'againstElectronVTightMVA6' 'againstMuonLoose3' 'againstMuonTight3' 'byCombinedIsolationDeltaBetaCorrRaw3Hits' 'byIsolationMVArun2v1DBdR03oldDMwLTraw' 'byIsolationMVArun2v1DBnewDMwLTraw' 'byIsolationMVArun2v1DBoldDMwLTraw' 'byIsolationMVArun2v1PWdR03oldDMwLTraw' 'byIsolationMVArun2v1PWnewDMwLTraw' 'byIsolationMVArun2v1PWoldDMwLTraw' 'byLooseCombinedIsolationDeltaBetaCorr3Hits' 'byLooseIsolationMVArun2v1DBdR03oldDMwLT' 'byLooseIsolationMVArun2v1DBnewDMwLT' 'byLooseIsolationMVArun2v1DBoldDMwLT' 'byLooseIsolationMVArun2v1PWdR03oldDMwLT' 'byLooseIsolationMVArun2v1PWnewDMwLT' 'byLooseIsolationMVArun2v1PWoldDMwLT' 'byMediumCombinedIsolationDeltaBetaCorr3Hits' 'byMediumIsolationMVArun2v1DBdR03oldDMwLT' 'byMediumIsolationMVArun2v1DBnewDMwLT' 'byMediumIsolationMVArun2v1DBoldDMwLT' 'byMediumIsolationMVArun2v1PWdR03oldDMwLT' 'byMediumIsolationMVArun2v1PWnewDMwLT' 'byMediumIsolationMVArun2v1PWoldDMwLT' 'byPhotonPtSumOutsideSignalCone' 'byTightCombinedIsolationDeltaBetaCorr3Hits' 'byTightIsolationMVArun2v1DBdR03oldDMwLT' 'byTightIsolationMVArun2v1DBnewDMwLT' 'byTightIsolationMVArun2v1DBoldDMwLT' 'byTightIsolationMVArun2v1PWdR03oldDMwLT' 'byTightIsolationMVArun2v1PWnewDMwLT' 'byTightIsolationMVArun2v1PWoldDMwLT' 'byVLooseIsolationMVArun2v1DBdR03oldDMwLT' 'byVLooseIsolationMVArun2v1DBnewDMwLT' 'byVLooseIsolationMVArun2v1DBoldDMwLT' 'byVLooseIsolationMVArun2v1PWdR03oldDMwLT' 'byVLooseIsolationMVArun2v1PWnewDMwLT' 'byVLooseIsolationMVArun2v1PWoldDMwLT' 'byVTightIsolationMVArun2v1DBdR03oldDMwLT' 'byVTightIsolationMVArun2v1DBnewDMwLT' 'byVTightIsolationMVArun2v1DBoldDMwLT' 'byVTightIsolationMVArun2v1PWdR03oldDMwLT' 'byVTightIsolationMVArun2v1PWnewDMwLT' 'byVTightIsolationMVArun2v1PWoldDMwLT' 'byVVLooseIsolationMVArun2v1DBdR03oldDMwLT' 'byVVLooseIsolationMVArun2v1DBnewDMwLT' 'byVVLooseIsolationMVArun2v1DBoldDMwLT' 'byVVTightIsolationMVArun2v1DBdR03oldDMwLT' 'byVVTightIsolationMVArun2v1DBnewDMwLT' 'byVVTightIsolationMVArun2v1DBoldDMwLT' 'byVVTightIsolationMVArun2v1PWdR03oldDMwLT' 'byVVTightIsolationMVArun2v1PWnewDMwLT' 'byVVTightIsolationMVArun2v1PWoldDMwLT' 'chargedIsoPtSum' 'chargedIsoPtSumdR03' 'decayModeFinding' 'decayModeFindingNewDMs' 'footprintCorrection' 'footprintCorrectiondR03' 'neutralIsoPtSum' 'neutralIsoPtSumWeight' 'neutralIsoPtSumWeightdR03' 'neutralIsoPtSumdR03' 'photonPtSumOutsideSignalCone' 'photonPtSumOutsideSignalConedR03' 'puCorrPtSum' 'byDeepTau2017v2VSeraw' 'byDeepTau2017v2VSjetraw' 'byDeepTau2017v2VSmuraw' 'byLooseDeepTau2017v2VSe' 'byLooseDeepTau2017v2VSjet' 'byLooseDeepTau2017v2VSmu' 'byMediumDeepTau2017v2VSe' 'byMediumDeepTau2017v2VSjet' 'byMediumDeepTau2017v2VSmu' 'byTightDeepTau2017v2VSe' 'byTightDeepTau2017v2VSjet' 'byTightDeepTau2017v2VSmu' 'byVLooseDeepTau2017v2VSe' 'byVLooseDeepTau2017v2VSjet' 'byVLooseDeepTau2017v2VSmu' 'byVTightDeepTau2017v2VSe' 'byVTightDeepTau2017v2VSjet' 'byVVLooseDeepTau2017v2VSe' 'byVVLooseDeepTau2017v2VSjet' 'byVVTightDeepTau2017v2VSe' 'byVVTightDeepTau2017v2VSjet' 'byVVVLooseDeepTau2017v2VSe' 'byVVVLooseDeepTau2017v2VSjet' 'againstElectronLooseMVA62018' 'againstElectronMVA6Raw2018' 'againstElectronMVA6category2018' 'againstElectronMediumMVA62018' 'againstElectronTightMVA62018' 'againstElectronVLooseMVA62018' 'againstElectronVTightMVA62018' 'byIsolationMVArun2v1DBdR03oldDMwLTraw2017v2' 'byIsolationMVArun2v1DBnewDMwLTraw2017v2' 'byIsolationMVArun2v1DBoldDMwLTraw2015' 'byIsolationMVArun2v1DBoldDMwLTraw2017v2' 'byLooseIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byLooseIsolationMVArun2v1DBnewDMwLT2017v2' 'byLooseIsolationMVArun2v1DBoldDMwLT2015' 'byLooseIsolationMVArun2v1DBoldDMwLT2017v2' 'byMediumIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byMediumIsolationMVArun2v1DBnewDMwLT2017v2' 'byMediumIsolationMVArun2v1DBoldDMwLT2015' 'byMediumIsolationMVArun2v1DBoldDMwLT2017v2' 'byTightIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byTightIsolationMVArun2v1DBnewDMwLT2017v2' 'byTightIsolationMVArun2v1DBoldDMwLT2015' 'byTightIsolationMVArun2v1DBoldDMwLT2017v2' 'byVLooseIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVLooseIsolationMVArun2v1DBnewDMwLT2017v2' 'byVLooseIsolationMVArun2v1DBoldDMwLT2015' 'byVLooseIsolationMVArun2v1DBoldDMwLT2017v2' 'byVTightIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVTightIsolationMVArun2v1DBnewDMwLT2017v2' 'byVTightIsolationMVArun2v1DBoldDMwLT2015' 'byVTightIsolationMVArun2v1DBoldDMwLT2017v2' 'byVVLooseIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVVLooseIsolationMVArun2v1DBnewDMwLT2017v2' 'byVVLooseIsolationMVArun2v1DBoldDMwLT2017v2' 'byVVTightIsolationMVArun2v1DBdR03oldDMwLT2017v2' 'byVVTightIsolationMVArun2v1DBnewDMwLT2017v2' 'byVVTightIsolationMVArun2v1DBoldDMwLT2015' 'byVVTightIsolationMVArun2v1DBoldDMwLT2017v2' .
> > ----- End Fatal Exception -------------------------------------------------
> > ```
> 
> @mariadalfonso @gouskos @fabiocos @peruzzim The problem is still there in 10_6_5, deepTau iDs are still not available

for completeness, this can be fixed if one uses this recipe
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePFTauID#Running_of_the_DeepTauIDs_ver_20
