### ISSUE TITLE
Finalization of CMSSW_11_0_X open development

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#28455]
I collect here the features that have been discussed as strongly desirable for the closure of the open integration of CMSSW_11_0_X , in view of HLT TDR production, Run3 tests and UL validation:

- [x] #28301 (new pythia8 243, it makes sense to update before a new production campaign)

- [x] #28385 (HGCAL trigger, almost ready, @rekovic please review)

- [x] #28466 (EGM regression for 2016 UL)

- [x] #28433 (BTL OOT pileup, affects RAW beyond L1T TDR description, to be validated)

- [x] #28441 (Run3 Tracker conditions)

- [ ] #28442 (PF in HF for phase2, mentioned in RECO list by @slava77 and @perrotta , but probably not a show-stopper)

- [x] #28446 (Remove MTD fastsim)

- [ ] #28448 (Phase2 tracker template CPE)

- [x] #28463 (HGcal scintillator digitization)

One more phase2 PR by tracker is expected and requested as important, @emiglior please point to that when available. 

Besides this it would be highly desirable to close the long pending #28247 and #28351 updates from DQM (basis for further developments).

Other phase2 updates are so far considered "nice to have".

@kpedro88 @fwyzard @trtomei @srimanob FYI, please comment/correct in case

**Comment by fabiocos** [comment]
@emiglior I understand the desired update it #28448 , please confirm

**Comment by mmusich** [comment]
> @emiglior I understand the desired update it #28448 , please confirm

Yes it is.

**Comment by kpedro88** [comment]
It would be good to include #28446, which cleans up some unneeded heavy items in the Phase 2 reco sequence.

**Comment by kpedro88** [comment]
#28463 should also be considered

**Comment by fwyzard** [comment]
#28442 does look like something we would like to have in, if possible.

**Comment by mariadalfonso** [comment]
Would be good to keep in the radar of the pre13 also the HCAL-TDC small update
https://github.com/cms-sw/cmssw/pull/28474
This PR target the Run3 and can be useful for the RAW production for L1 trigger studies.

**Comment by fabiocos** [comment]
From the notes of @kpedro88 at the ORP of 2019/11/26: the crucial PRs to close CMSSW_11_0_0_pre13 are #28466 #28433 #28463 .

On top of that #28495 is claimed as needed to prevent inconsistent results in L1T
