### ISSUE TITLE
[DD4hep] Algorithms review and refactoring

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#29997]
The DD4hep algorithms are almost a direct copy of the corresponding DD algorithms. The latter design required all objects to be named and registered in the global registries. This is not the case for the former.

A thorough code review is needed to clean unnecessary memory allocation, to prevent possible overlaps and ultimately improve code quality and performance.

Examples of proposed improvements include but not limited to removing the unneeded names - `string`s, removing a locally used object registration in the `namespace`, introducing an angular positioning with a tolerance, merging some of the algorithms to avoid duplication, etc.

@cvuosalo, @bsunanda, @civanch - IMHO it would be beneficial to do this before the geometry is validated and frozen.

- [x] Allow access to values in single precision PR #30093

- [x] Replace Torus with a simpler shape PR #30093

- [x] Use single precision PR #30093

- [x] DDEcalPreshower 20% improvement in memory consumption and performance PR #30093  

- [ ] TODO list all algorithms revised here..., list all PRs as well...

**Comment by makortel** [comment]
assign geometry

**Comment by cvuosalo** [comment]
@ianna Could you please clarify how algorithm optimization would affect or change geometry?
Also, how long do you think algorithm review and refactoring would take? It seems to me that it would take many months, and we have very few developers to do it. I don't see how we could finish it for 11_2.

**Comment by ianna** [comment]
> @ianna Could you please clarify how algorithm optimization would affect or change geometry?
The algorithms are an integral part of the CMS geometry description. Changing the C++ code is equivalent to changing the XML. 
> Also, how long do you think algorithm review and refactoring would take? It seems to me that it would take many months, and we have very few developers to do it. I don't see how we could finish it for 11_2.
A couple of days to review and the rest depending on the outcome of the review ~ couple of weeks? The ECal’s are definitely the most time consuming.

**Comment by dpiparo** [comment]
I am in favour of this work. Here you see an example of place where we can improve:
- http://innocent.web.cern.ch/innocent/perfResults/igprof-navigator/step4_PAT_PU_IB0608_CMSSW_11_2_X_2020-06-08-2300_slc7_amd64_gcc900/64
- https://cmssdt.cern.ch/lxr/source/Geometry/MTDNumberingBuilder/plugins/DDCmsMTDConstruction.cc:0025

**Comment by civanch** [comment]
I fully agree with this work. When we fix 11_1 Run-3 geometry we have a good benchmark for validation of updated algorithms.

**Comment by ianna** [comment]
> I am in favour of this work. Here you see an example of place where we can improve:
> 
> * http://innocent.web.cern.ch/innocent/perfResults/igprof-navigator/step4_PAT_PU_IB0608_CMSSW_11_2_X_2020-06-08-2300_slc7_amd64_gcc900/64
> * https://cmssdt.cern.ch/lxr/source/Geometry/MTDNumberingBuilder/plugins/DDCmsMTDConstruction.cc:0025

Yes, the links point to the DD implementation. We ought to do much better having completed the DD4hep migration :-)

**Comment by fabiocos** [comment]
@ianna @cvuosalo I believe that this result, which might seem odd, is subject to change when we move to DD4hep, where the logic of the loop in the MTD geometry building is different. Furthermore, geometry in the long run should be recovered from DB. And its use after reconstruction will also likely change. So I would be careful in spending a lot of time on this now.

**Comment by civanch** [comment]
@ianna , likely we resolved this issue?

**Comment by ianna** [comment]
closed in favour of https://github.com/cms-sw/cmssw/issues/34663
