### ISSUE TITLE
Handle DB payloads for Phase 2 geometries via (meta-)GTs

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#32357]
During the [CMS week Simulation meeting](https://indico.cern.ch/event/978153/#40-dd4hep-interface-survey), there was a discussion of using DB payloads for Phase 2 geometries to improve performance with DD4hep.

Previously, this idea had been disfavored because of the infeasibility of maintaining O(20) separate GT queues to handle all of the various Phase 2 geometry configurations.

However, to handle different tracker conditions for different subdetector versions, there are now "meta"-GTs in [autoCondPhase2.py](https://github.com/cms-sw/cmssw/blob/master/Configuration/AlCa/python/autoCondPhase2.py). This script starts from a baseline and then specifies different records for specific conditions for each tracker subdetector version.

This approach could be extended to create a "meta"-GT for each Phase 2 detector scenario with minimal maintenance required.

Possible development items:
- [ ] Add functionality to the [geometry script](https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/scripts/generate2026Geometry.py) to generate DB payloads automatically or on demand
- [ ] Make [autoCondPhase2.py](https://github.com/cms-sw/cmssw/blob/master/Configuration/AlCa/python/autoCondPhase2.py) import the available geometries and their components directly from the [geometry script](https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/scripts/generate2026Geometry.py) (automate creation of meta-GT for each geometry)
- [ ] Include a switch for upgrade workflows to swap between XML and DB geometries (development will still need to use XML)

attn: @civanch @ianna @bsunanda

**Comment by kpedro88** [comment]
assign upgrade,geometry,alca

**Comment by ianna** [comment]
@kpedro88 and @bsunanda - we need to check that [an obsolete HGCal schema](https://cmssdt.cern.ch/lxr/source/CondFormats/GeometryObjects/interface/PHGCalParameters.h) was never uploaded to ProdDB **accidentally**. If that's the case, it can be safely deleted. Or, the class name can be reused to make it more generic as a set of std::vectors and std::maps without specific parameter names. 

However, if it was uploaded, we have to make sure that the payload is not included in the GT and we will have to come with a different class name.

**Comment by tvami** [comment]
Hi, I'm just reading open AlCa pending issues. The Phase-2 conditions are using the meta-GT https://github.com/cms-sw/cmssw/blob/master/Configuration/AlCa/python/autoCondPhase2.py for each geometry, so is this issue ready to be closed? @cms-sw/upgrade-l2 @cms-sw/geometry-l2

**Comment by srimanob** [comment]
@tvami 
If I understand from the original message, the proposal is to extend this tracker way to other detectors. Do you know their current situation?

**Comment by tvami** [comment]
Hi @cvuosalo do you maybe have a better view of what the plans are related to this issue?

**Comment by kpedro88** [comment]
The point of this issue is to use the meta-GT approach to enable the use of *geometry* DB files. Currently, all Phase 2 geometries are read from XML because it's prohibitive to maintain N separate GT queues.

**Comment by srimanob** [comment]
Ah, so the key point is that we can load DB geometries of all versions of all detectors and compose the GT. So, we have 1 queue only. Right? Yeah, this looks like a good way to move on, maybe for DD4hep.

**Comment by tvami** [comment]
@srimanob @bsunanda what is the timeline now for the Phase-2 DD4hep geometries?

**Comment by bsunanda** [comment]
Once we find one stable scenario for Phase2 description, we can think of either DDD or DD4Hep version to be loaded to DB. Currently only DDD versions for Phase2 geometries are running satisfactorily. We need to resolve the DD4hep issue and then reach a stable scenario. Both tracker and HGCal geometries are evolving and none of the Phase2 detectors have gone for "construction" phase as yet
________________________________

**Comment by tvami** [comment]
+alca
 * I'm signing this as an agreement from the AlCa side, the action items depend on the geometry team, not on AlCa
