### ISSUE TITLE
Towards CMSSW_11_2_0 - open issue

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#32465]
PPD General meeting ( Dec 10): https://indico.cern.ch/event/979274/

From https://cms-pdmv.cern.ch/valdb/?srch=11_2&selected=11_2_0_pre9_phase2,11_2_0_pre9_2021,11_2_0_pre10_phase2,11_2_0_pre11_2021&PAGs=true&PData=true&PFull=true&PFast=true&HLT=true&HData=true&HFull=true&GEN=true&GGen=true&IN=true&IData=true&IFull=true

![image](https://user-images.githubusercontent.com/6177433/102076458-ff121380-3e07-11eb-8f9e-5db0a20920b8.png)

The open issues are
- [ ] #32467 Run-3 L1T (see https://hypernews.cern.ch/HyperNews/CMS/get/relval/15254/34.html and https://its.cern.ch/jira/browse/CMSLITDPG-916)
- [x] #32466 MET phase2 (see https://hypernews.cern.ch/HyperNews/CMS/get/relval/15255/18.html)
- [ ] #32475 No endcap electrons in phase2 (miniAOD)

@chayanit @jordan-martins @rappoccio please comment if something is missing

**Comment by silviodonato** [comment]
assign pdmv

**Comment by qliphy** [comment]
As discussed at today's ORP, this issue can be closed now.  11_2_0 validation is successful according to PPD report on Jan 7th.
