### ISSUE TITLE
features for bParking UL rereco and miniAOD in 10_6_X (10_6_26?)

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#33917]
This issue is to collect PRs/features for integration towards b-parking dataset rereco and miniAOD in 10_6_X 

Deadline for integration is June 7, 2021 (PRs should be merged by this date)

RECO/AOD part:
- no modifications are expected

miniAOD:
- [ ] #33589 lowPt electrons ID and regression 
- [ ] #33878: Adding the correction structure to all electrons
- [ ] #33877 Making miniAOD low pt tracks threshold tunable
- [ ] (backport is needed for) #33891 Adding Xi-compatible tracks to lostTracks collection
- [ ] (PR is needed for ) #33665 to define test workflows 

@cms-sw/xpog-l2 
please check the list and clarify if more is needed/planned

**Comment by slava77** [comment]
assign reconstruction,xpog

**Comment by slava77** [comment]
@rappoccio (tagging for PPD, I don't have Andreas' git at hand)

**Comment by slava77** [comment]
from https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1716/1.html
code introduced in #33774 is discussed (potentially) as an addition in the MC dataset processing. 
@mtosi @vmariani

**Comment by slava77** [comment]
updates in the issue description/list from earlier today:

New:
    - #33922 "Adding offlineVerticesWithBS to miniAOD" was added to the list (master version #33778 was merged May 28)
- Status update:
    - #33877 Making miniAOD low pt tracks threshold tunable (merged June 1, 2021)
    - notes for other PRs were extended to mention the master PR (where it was not already mentioned)

**Comment by mariadalfonso** [comment]
There is the idea to keep the muonHits in AOD or a reduced collection in miniAOD.
was discussed at PC-coord may26 and PPD-coord june2
Marco Pieri will follow up with proponents

**Comment by slava77** [comment]
> There is the idea to keep the muonHits in AOD or a reduced collection in miniAOD. The idea is to enable some EXO analysis on the B-parking dataset. It was discussed at PC-coord may26 and PPD-coord june2
> Marco Pieri will follow up with proponents

isn't this enabled by default in AOD?
or is it about something other than what was added in #31350 in 10_6_17?

**Comment by slava77** [comment]
> > There is the idea to keep the muonHits in AOD or a reduced collection in miniAOD. The idea is to enable some EXO analysis on the B-parking dataset. It was discussed at PC-coord may26 and PPD-coord june2
> > Marco Pieri will follow up with proponents
> 
> isn't this enabled by default in AOD?
> or is it about something other than what was added in #31350 in 10_6_17?

based on the discussion in the PPD today, this is different, to include all muon rechits 
```
• Muon system acts like a sampling calorimeter
• LLP decays produce a shower of particles
• RecHits used to form clusters and identify a signal
```
IIUC, there is no plan to keep AOD on disk for this processing. Are the analyses targeting this set up to use miniAOD for parts other than muon hits?

**Comment by rappoccio** [comment]
Correct, we don't have any plans to keep this on disk, but if we do a future miniaod (v3) later, it would be available.

**Comment by AdrianoDee** [comment]
From the low pt tracks point of view, we should be fine. Thanks a lot for the (super fast) effort done for reviewing the code!

**Comment by slava77** [comment]
current status of the list of features
<img width="620" alt="Screen Shot 2021-06-04 at 7 22 36 AM" src="https://user-images.githubusercontent.com/4676718/120816569-b9f0b380-c505-11eb-8f11-7eb74d4f166b.png">

I added two PRs which are described as targeting nanoAOD (v9), but they also include modifications in the miniAOD products. Both a backport of #33817 and #33759 will need to appropriately disable the updates in miniAOD except for `bParking | run2_miniAOD_devel` to follow the no-change policy for the existing old miniAOD production(s).

**Comment by slava77** [comment]
I updated the list with the following:

RECO/AOD part:
- #34066 Add CSC/DT rechits to AOD
- MC-specific: 
    -  #33996 Track-gen matching passing through TrackingParticle
    -  NEED A PATCH TO CMSSW_10_2_16_UL with keep statements from #33996  in SimTracker/Configuration/python/SimTracker_EventContent_cff.py

**Comment by slava77** [comment]
>     * NEED A PATCH TO CMSSW_10_2_16_UL with keep statements from #33996  in SimTracker/Configuration/python/SimTracker_EventContent_cff.py

the above came from the discussion in https://github.com/cms-sw/cmssw/pull/33996#issuecomment-858084961

@silviodonato @qliphy 
what is your preference to make this update?
There is no branch for patches for CMSSW_10_2_16 ( = CMSSW_10_2_16_UL). Should the update be made to CMSSW_10_2_X? (The difference is more than a few files https://github.com/cms-sw/cmssw/compare/CMSSW_10_2_16_UL..CMSSW_10_2_X)

**Comment by qliphy** [comment]
probably we can make CMSSW_10_2_26_patch2 ?  @silviodonato  may comment more.

**Comment by silviodonato** [comment]
@slava77 once we have a backport of  #33996 to CMSSW_10_2_X, we can build a special `CMSSW_10_2_16_UL2` that is `CMSSW_10_2_16_UL` + backport of  #33996.
The file differences should be harmless, but I think it is more safe to avoid the big jump `CMSSW_10_2_16_UL` -> `CMSSW_10_2_27_UL` only for b-parking UL.

@smuzaffar what is the best way to build a `CMSSW_10_2_16_UL2` from the technical point of view?
Do we need a new branch `CMSSW_10_2_16_UL_patchX` or can we directly cherry-pick the commits that we want to add?

**Comment by smuzaffar** [comment]
@silviodonato , if `CMSSW_10_2_16_UL2` should be `CMSSW_10_2_16_UL` +  #33996 then we need a cmssw tag or branch with `CMSSW_10_2_16_UL +  #33996`  which you can use as CMSSW_COMMIT in the build issue.

**Comment by smuzaffar** [comment]
and you also should use 
```
CMSDIST_COMMIT=REL/CMSSW_10_2_16_UL/slc7_amd64_gcc700
PRODUCTION_ARCHITECTURE:slc7_amd64_gcc700
```
in order to not get all the external merged in `IB/CMSSW_10_2_X/gcc700` branch

**Comment by slava77** [comment]
> @silviodonato , if `CMSSW_10_2_16_UL2` should be `CMSSW_10_2_16_UL` + #33996 then we need a cmssw tag or branch with `CMSSW_10_2_16_UL + #33996` which you can use as CMSSW_COMMIT in the build issue.

I'm not familiar with this procedure, in the past we used PRs to make updates.

So, somebody will
- checkout CMSSW_10_2_16_UL in "from-CMSSW_10_2_16_UL" branch
- add a commit on it
- push it to the personal remote
- ... what's next?

**Comment by silviodonato** [comment]
I would say - first of all - to merge the 102X backport  to the standard `CMSSW_10_2_X`.

Then, I've just created the branch `CMSSW_10_2_16_UL_patchX`, so you can make a PR towards `CMSSW_10_2_16_UL_patchX` and then we'll build the release

**Comment by qliphy** [comment]
@smuzaffar @silviodonato   
Please check whether this is ok:
https://github.com/cms-sw/cmssw/issues/34089

**Comment by slava77** [comment]
> @smuzaffar @silviodonato
> Please check whether this is ok:
> #34089

the tag looks correct:
https://github.com/cms-sw/cmssw/compare/CMSSW_10_2_16_UL...CMSSW_10_2_16_UL2

**Comment by qliphy** [comment]
superseded by https://github.com/cms-sw/cmssw/issues/34090  thanks to @smuzaffar

**Comment by qliphy** [comment]
CMSSW_10_2_16_UL2  is now ready
https://github.com/cms-sw/cmssw/releases/CMSSW_10_2_16_UL2

**Comment by slava77** [comment]
Current status is now down to one PR: 
- #33996 "Track-gen matching passing through TrackingParticle" still needs the master version #33774 to get through, which is  missing pdmv and upgrade signatures

The other incomplete item is " to define test workflows" could probably be done now outside of the cmssw source.

**Comment by slava77** [comment]
it looks like all PRs are now merged

**Comment by slava77** [comment]
@cms-sw/pdmv-l2 

this is connected with the MC setup discussion earlier today.
When I closed the issue I thought that the MC production was done/in progress as well.
