### ISSUE TITLE
mkFit To-Do list

### ISSUE THREAD

**Issue by clacaputo** [cms-sw/cmssw#36966]
The issue is intended to keep track of the *mkFit* pending to-do items coming from **[mkFit external integration](https://github.com/cms-sw/cmssw/pull/36546#)** that are going to be addressed in future PRs.
The list has been taken from https://github.com/cms-sw/cmssw/pull/36546#issuecomment-1039168783

#### Short/medium term

- [ ] Get Magnetic field from EventSetup (shorter term)
- [ ] Make the minCCC configurable (currently hardcoded as `kMinChargePerCM = 1620`) (shorter term)
- [ ] Get rid of (or avoid?) a copy of enum class TrackAlgorithm and related strings (copied from reco::Track) (shorter/medium term)
    - use cases in `runFunctions.cc` should better just use the IterationConfig correctly `WriteMemoryFile.cc` needs to check only for iter0: can hardcode this
    - IterationConfig.cc (uses the string names) could perhaps be dependent on CMSSW DataFormats/TrackReco/interface/TrackBase.h
- [ ] magic numbers (repeated literals) in layer indexing (short term)

#### Long term

- [ ] Cleanup of `CMS-2017.cc`, `CMS-2017.acc`, and `CMS-2017-HitSelectionWindows.h` .vs. `createPhase1TrackerGeometry.cc`, `createPhase1TrackerGeometryAutoGen.acc`
    - fix with proper mkfit geometry extraction in CMSSW (longer term)
https://github.com/cms-sw/cmssw/pull/36546#discussion_r782525389
https://github.com/cms-sw/cmssw/pull/36546#discussion_r783219283
- [ ] Cleanup and remove `Ice/`
    - fix with the usage of binnor in seed-sorting, check radix-sort vs. std::sort
https://github.com/cms-sw/cmssw/pull/36546#discussion_r783264814
… and following 4 comments.
    - remove `-Wno-error=strict-aliasing` from `RecoTracker/MkFitCore/BuildFile.xml`(short term)
- [ ] material description from reco geometry/ES
https://github.com/cms-sw/cmssw/pull/36546#discussion_r784175175
(there are also arrays of constants in Config.h) (longer term)
- [ ] Re-consollidate BH / Std / CE / MIMI so all methods can be used again. 
    - use same seed cleaning / dup-removal functions, clean out old ones. (longer term)
- [ ] Improve/properly treat 0 Tesla case (longer term)

**Comment by clacaputo** [comment]
assign reconstruction

**Comment by clacaputo** [comment]
assign @cms-sw/tracking-pog-l2

**Comment by clacaputo** [comment]
FYI @mmasciov @osschar

**Comment by jpata** [comment]
type tracking

@clacaputo can you update the PR, ticking what was already implemented? (only the author can)

**Comment by slava77** [comment]
> Cleanup of `CMS-2017.cc`, `CMS-2017.acc`, and `CMS-2017-HitSelectionWindows.h` .vs. `createPhase1TrackerGeometry.cc`, `createPhase1TrackerGeometryAutoGen.acc`
> 
>     * fix with proper mkfit geometry extraction in CMSSW (longer term)

I think that this one was addressed in #37418 

while 
> material description from reco geometry/ES

is not addressed yet
