### ISSUE TITLE
Remaining issues after the merging of "L1T Phase-2, remove old simulation and adapt DQM (#38442)"

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#39194]
The PR in object was merged in time for 12_5_0_pre5, but there were several issues that remained open, and that should all get fixed as soon as possible, and in any case before the final 12_5_0.
If I did not forget anything, the list of the still open issues is the following:

- [x] Change modules and class member names to lowercase, see https://github.com/cms-sw/cmssw/pull/38442#issuecomment-1223694816 (see also https://github.com/cms-sw/cmssw/issues/39194#issuecomment-1227453037)

- [x] Fix `hltTriggerSummaryAOD`, see https://github.com/cms-sw/cmssw/pull/38442#issuecomment-1225444447

- [x] change the interface of the `TrackerMuon` module (i.e. the configuration parameters) to take a single list of qualities, instead of the more complex approach there is now, see https://github.com/cms-sw/cmssw/pull/38442#pullrequestreview-1081627993

- [x] Check the defaults in `detQualDefault.addParameter<std::vector<int>>("qualities", {-99, -99, -99})`, see https://github.com/cms-sw/cmssw/pull/38442#discussion_r952261411

- [x] Verify the PSet `cutset` in `L1TrackSelectionProducerExtended` , cloned from  `L1TrackSelectionProducer` in L1Trigger/L1TTrackMatch/python/L1TrackSelectionProducer_cfi.py (as it was different in #38442 before the last commits: not clear if it was modified on purpose or by mistake)

- [x] After the merging of #38442 we are noticing spurios differences in the efficiencies for Phase2 muons in DQM in the PR tests, see e.g. https://github.com/cms-sw/cmssw/pull/39209 and https://github.com/cms-sw/cmssw/pull/39193

@cecilecaillol @trtomei @BenjaminRS ...
@fwyzard @jpata @missirol @Martin-Grunewald @AdrianoDee @srimanob ...

**Comment by perrotta** [comment]
assign @cms-sw/l1-l2

**Comment by missirol** [comment]
assign l1

(based on https://github.com/cms-sw/cmssw/issues/39194#issuecomment-1227414925 ; thanks @perrotta for opening the issue.)

Regarding item-1, I think the main point is the introduction of a naming convention, e.g. `l1t[Module]` (in addition to starting with lowercase letters), as mentioned in
https://github.com/cms-sw/cmssw/pull/38442#discussion_r952263162
https://github.com/cms-sw/cmssw/pull/38442#discussion_r952277982
https://github.com/cms-sw/cmssw/pull/38442#issuecomment-1223694816

**Comment by missirol** [comment]
assign hlt

Items-2,3,4 concern the HLT Phase-2 menu (@trtomei).

**Comment by cecilecaillol** [comment]
Item 5: The differences in cutset are only formatting, there is no change to the values

**Comment by perrotta** [comment]
> Item 5: The differences in cutset are only formatting, there is no change to the values

Thank you Cecile. There were a few differences in the parameters included in the `cutset` PSet of the module `L1TrackSelectionProducerExtended` between the original commits of yours in the PR and what finally got merged. The modifications that got removed in your latest commits are:
```PYTHON
  cutset = dict(ptmin = 3.,# pt must be greater than this value, [GeV]
                reducedBendChi2Max = 2.4, # bend chi2 must be less than this value
                reducedChi2RZMax = 10.0, # chi2rz/dof must be less than this value
                reducedChi2RPhiMax = 40.0, # chi2rphi/dof must be less than this value
                deltaZMax = [3.0, 3.0, 3.0, 3.0, 3.0, 3.0], # delta z must be less than these values, there will be one less value here than in deltaZMaxEtaBounds, [cm]
            ),
```
That item 5 intended just to check with you whether the removal of those modifications of the parametere were intentional (then everything is fine), or if they were just forgotten at the end (and therefore they should be reimplemented if so).

**Comment by cecilecaillol** [comment]
> > Item 5: The differences in cutset are only formatting, there is no change to the values
> 
> Thank you Cecile. There were a few differences in the parameters included in the `cutset` PSet of the module `L1TrackSelectionProducerExtended` between the original commits of yours in the PR and what finally got merged. The modifications that got removed in your latest commits are:
> 
> ```python
>   cutset = dict(ptmin = 3.,# pt must be greater than this value, [GeV]
>                 reducedBendChi2Max = 2.4, # bend chi2 must be less than this value
>                 reducedChi2RZMax = 10.0, # chi2rz/dof must be less than this value
>                 reducedChi2RPhiMax = 40.0, # chi2rphi/dof must be less than this value
>                 deltaZMax = [3.0, 3.0, 3.0, 3.0, 3.0, 3.0], # delta z must be less than these values, there will be one less value here than in deltaZMaxEtaBounds, [cm]
>             ),
> ```
> 
> That item 5 intended just to check with you whether the removal of those modifications of the parametere were intentional (then everything is fine), or if they were just forgotten at the end (and therefore they should be reimplemented if so).

Sorry, I am still confused. I see these parameters are present and unchanged in the current L1TrackSelectionProducerExtended configuration: https://github.com/cecilecaillol/cmssw/blob/f6c5d02e18f03e70fc6f95a58c8e0782770d356e/L1Trigger/L1TTrackMatch/python/L1TrackSelectionProducer_cfi.py#L33-L44. Am I missing something?

**Comment by perrotta** [comment]
> Sorry, I am still confused. I see these parameters are present and unchanged in the current L1TrackSelectionProducerExtended configuration: https://github.com/cecilecaillol/cmssw/blob/f6c5d02e18f03e70fc6f95a58c8e0782770d356e/L1Trigger/L1TTrackMatch/python/L1TrackSelectionProducer_cfi.py#L33-L44. Am I missing something?

I was probably looking at some intermediate version of that file, where the `cutset` PSet was missing in the cloned config... Nevertheless, the original comment was to remove the type specifications in the parameters (whch is safer, cleaner, etc.). Therefore, the cloned config can be rewritten as
```PYTHON
L1TrackSelectionProducerExtended = L1TrackSelectionProducer.clone(
  l1TracksInputTag = ("L1GTTInputProducerExtended","Level1TTTracksExtendedConverted"),
  outputCollectionName = "Level1TTTracksExtendedSelected",
  cutset = dict(ptmin = 3.,# pt must be greater than this value, [GeV]
                reducedBendChi2Max = 2.4, # bend chi2 must be less than this value
                reducedChi2RZMax = 10.0, # chi2rz/dof must be less than this value
                reducedChi2RPhiMax = 40.0, # chi2rphi/dof must be less than this value
                deltaZMax = [3.0, 3.0, 3.0, 3.0, 3.0, 3.0], # delta z must be less than these values, there will be one less value here than in deltaZMaxEtaBounds, [cm]
            ),
  useDisplacedTracksDeltaZOverride = 3.0 # Use promt/displaced tracks
)
```

**Comment by cecilecaillol** [comment]
@trtomei I took care of item 2. Can you please address items 3 and 4?

**Comment by trtomei** [comment]
Yes, it's on my TODO list for today :)

**Comment by perrotta** [comment]
urgent
(To make it visible in the list of issues: item 6, in particular, keeps messing the Phase2 DQM comparisons in the PR tests)

**Comment by trtomei** [comment]
Pull requests to address items 3 and 4 are here:
https://github.com/cms-sw/cmssw/pull/39280
https://github.com/cms-sw/cmssw/pull/39281

**Comment by perrotta** [comment]
Items (2) and (3) addressed by https://github.com/cms-sw/cmssw/pull/39280 and ticked in the main description

**Comment by trtomei** [comment]
@perrotta #39280 actually addresses items (3) and (4), item (2) was previously fixed by Cecile.

**Comment by perrotta** [comment]
#39283 was not able to fix item 6, because also after its merge in CMSSW_12_6_X_2022-09-02-1100 the PR tests continue to show non reproducible results for L1T muon global efficiencies, both SA and Tracker muons, e.g.L

**Comment by perrotta** [comment]
Itemo 6 got fixed by #39301: thank you @missirol for it!

**Comment by cecilecaillol** [comment]
Items 1, 2, and 5 fixed in https://github.com/cms-sw/cmssw/pull/38442

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
A fix for item 5 was included in #39244
All them have been addressed then, and this issue can be closed

**Comment by missirol** [comment]
+hlt
